// Code generated by wadge-bindgen-go DO NOT EDIT

package main_test

import (
	github_com__bytecodealliance__wasm___tools___go__cm "github.com/bytecodealliance/wasm-tools-go/cm"
	wadge "github.com/wasmCloud/wadge"
	github_com__wasmCloud__wadge__examples__go__http__bindings__wasi__clocks__monotonic___clock "github.com/wasmCloud/wadge/examples/go/http/bindings/wasi/clocks/monotonic-clock"
	github_com__wasmCloud__wadge__examples__go__http__bindings__wasi__http__types "github.com/wasmCloud/wadge/examples/go/http/bindings/wasi/http/types"
	github_com__wasmCloud__wadge__examples__go__http__bindings__wasi__io__poll "github.com/wasmCloud/wadge/examples/go/http/bindings/wasi/io/poll"
	github_com__wasmCloud__wadge__examples__go__http__bindings__wasi__io__streams "github.com/wasmCloud/wadge/examples/go/http/bindings/wasi/io/streams"
	"runtime"
	"unsafe"
)

const _ string = runtime.Compiler

var _ unsafe.Pointer

//go:linkname wasmimport_Now github.com/wasmCloud/wadge/examples/go/http/bindings/wasi/clocks/monotonic-clock.wasmimport_Now
func wasmimport_Now() (result0 uint64) {
	var __p runtime.Pinner
	defer __p.Unpin()
	if __err := wadge.WithCurrentInstance(func(__instance *wadge.Instance) error {
		return __instance.Call("wasi:clocks/monotonic-clock@0.2.0", "now", func() unsafe.Pointer {
			ptr := unsafe.Pointer(&result0)
			__p.Pin(ptr)
			return ptr
		}())
	}); __err != nil {
		wadge.CurrentErrorHandler()(__err)
	}
	return
}

//go:linkname wasmimport_Resolution github.com/wasmCloud/wadge/examples/go/http/bindings/wasi/clocks/monotonic-clock.wasmimport_Resolution
func wasmimport_Resolution() (result0 uint64) {
	var __p runtime.Pinner
	defer __p.Unpin()
	if __err := wadge.WithCurrentInstance(func(__instance *wadge.Instance) error {
		return __instance.Call("wasi:clocks/monotonic-clock@0.2.0", "resolution", func() unsafe.Pointer {
			ptr := unsafe.Pointer(&result0)
			__p.Pin(ptr)
			return ptr
		}())
	}); __err != nil {
		wadge.CurrentErrorHandler()(__err)
	}
	return
}

//go:linkname wasmimport_SubscribeDuration github.com/wasmCloud/wadge/examples/go/http/bindings/wasi/clocks/monotonic-clock.wasmimport_SubscribeDuration
func wasmimport_SubscribeDuration(when0 uint64) (result0 uint32) {
	var __p runtime.Pinner
	defer __p.Unpin()
	if __err := wadge.WithCurrentInstance(func(__instance *wadge.Instance) error {
		return __instance.Call("wasi:clocks/monotonic-clock@0.2.0", "subscribe-duration", func() unsafe.Pointer {
			ptr := unsafe.Pointer(&when0)
			__p.Pin(ptr)
			return ptr
		}(), func() unsafe.Pointer {
			ptr := unsafe.Pointer(&result0)
			__p.Pin(ptr)
			return ptr
		}())
	}); __err != nil {
		wadge.CurrentErrorHandler()(__err)
	}
	return
}

//go:linkname wasmimport_SubscribeInstant github.com/wasmCloud/wadge/examples/go/http/bindings/wasi/clocks/monotonic-clock.wasmimport_SubscribeInstant
func wasmimport_SubscribeInstant(when0 uint64) (result0 uint32) {
	var __p runtime.Pinner
	defer __p.Unpin()
	if __err := wadge.WithCurrentInstance(func(__instance *wadge.Instance) error {
		return __instance.Call("wasi:clocks/monotonic-clock@0.2.0", "subscribe-instant", func() unsafe.Pointer {
			ptr := unsafe.Pointer(&when0)
			__p.Pin(ptr)
			return ptr
		}(), func() unsafe.Pointer {
			ptr := unsafe.Pointer(&result0)
			__p.Pin(ptr)
			return ptr
		}())
	}); __err != nil {
		wadge.CurrentErrorHandler()(__err)
	}
	return
}

//go:linkname wasmimport_NewFields github.com/wasmCloud/wadge/examples/go/http/bindings/wasi/http/types.wasmimport_NewFields
func wasmimport_NewFields() (result0 uint32) {
	var __p runtime.Pinner
	defer __p.Unpin()
	if __err := wadge.WithCurrentInstance(func(__instance *wadge.Instance) error {
		return __instance.Call("wasi:http/types@0.2.0", "[constructor]fields", func() unsafe.Pointer {
			ptr := unsafe.Pointer(&result0)
			__p.Pin(ptr)
			return ptr
		}())
	}); __err != nil {
		wadge.CurrentErrorHandler()(__err)
	}
	return
}

//go:linkname wasmimport_NewOutgoingRequest github.com/wasmCloud/wadge/examples/go/http/bindings/wasi/http/types.wasmimport_NewOutgoingRequest
func wasmimport_NewOutgoingRequest(headers0 uint32) (result0 uint32) {
	var __p runtime.Pinner
	defer __p.Unpin()
	if __err := wadge.WithCurrentInstance(func(__instance *wadge.Instance) error {
		return __instance.Call("wasi:http/types@0.2.0", "[constructor]outgoing-request", func() unsafe.Pointer {
			ptr := unsafe.Pointer(&headers0)
			__p.Pin(ptr)
			return ptr
		}(), func() unsafe.Pointer {
			ptr := unsafe.Pointer(&result0)
			__p.Pin(ptr)
			return ptr
		}())
	}); __err != nil {
		wadge.CurrentErrorHandler()(__err)
	}
	return
}

//go:linkname wasmimport_NewOutgoingResponse github.com/wasmCloud/wadge/examples/go/http/bindings/wasi/http/types.wasmimport_NewOutgoingResponse
func wasmimport_NewOutgoingResponse(headers0 uint32) (result0 uint32) {
	var __p runtime.Pinner
	defer __p.Unpin()
	if __err := wadge.WithCurrentInstance(func(__instance *wadge.Instance) error {
		return __instance.Call("wasi:http/types@0.2.0", "[constructor]outgoing-response", func() unsafe.Pointer {
			ptr := unsafe.Pointer(&headers0)
			__p.Pin(ptr)
			return ptr
		}(), func() unsafe.Pointer {
			ptr := unsafe.Pointer(&result0)
			__p.Pin(ptr)
			return ptr
		}())
	}); __err != nil {
		wadge.CurrentErrorHandler()(__err)
	}
	return
}

//go:linkname wasmimport_NewRequestOptions github.com/wasmCloud/wadge/examples/go/http/bindings/wasi/http/types.wasmimport_NewRequestOptions
func wasmimport_NewRequestOptions() (result0 uint32) {
	var __p runtime.Pinner
	defer __p.Unpin()
	if __err := wadge.WithCurrentInstance(func(__instance *wadge.Instance) error {
		return __instance.Call("wasi:http/types@0.2.0", "[constructor]request-options", func() unsafe.Pointer {
			ptr := unsafe.Pointer(&result0)
			__p.Pin(ptr)
			return ptr
		}())
	}); __err != nil {
		wadge.CurrentErrorHandler()(__err)
	}
	return
}

//go:linkname wasmimport_FieldsAppend github.com/wasmCloud/wadge/examples/go/http/bindings/wasi/http/types.wasmimport_FieldsAppend
func wasmimport_FieldsAppend(self0 uint32, name0 *uint8, name1 uint32, value0 *uint8, value1 uint32, result *github_com__bytecodealliance__wasm___tools___go__cm.Result[github_com__wasmCloud__wadge__examples__go__http__bindings__wasi__http__types.HeaderError, struct{}, github_com__wasmCloud__wadge__examples__go__http__bindings__wasi__http__types.HeaderError]) {
	var __p runtime.Pinner
	defer __p.Unpin()
	if __err := wadge.WithCurrentInstance(func(__instance *wadge.Instance) error {
		return __instance.Call("wasi:http/types@0.2.0", "[method]fields.append", func() unsafe.Pointer {
			ptr := unsafe.Pointer(&self0)
			__p.Pin(ptr)
			return ptr
		}(), func() unsafe.Pointer {
			ptr := unsafe.Pointer(name0)
			__p.Pin(ptr)
			return ptr
		}(), func() unsafe.Pointer {
			ptr := unsafe.Pointer(&name1)
			__p.Pin(ptr)
			return ptr
		}(), func() unsafe.Pointer {
			ptr := unsafe.Pointer(value0)
			__p.Pin(ptr)
			return ptr
		}(), func() unsafe.Pointer {
			ptr := unsafe.Pointer(&value1)
			__p.Pin(ptr)
			return ptr
		}(), func() unsafe.Pointer {
			ptr := unsafe.Pointer(result)
			__p.Pin(ptr)
			return ptr
		}())
	}); __err != nil {
		wadge.CurrentErrorHandler()(__err)
	}
	return
}

//go:linkname wasmimport_FieldsClone github.com/wasmCloud/wadge/examples/go/http/bindings/wasi/http/types.wasmimport_FieldsClone
func wasmimport_FieldsClone(self0 uint32) (result0 uint32) {
	var __p runtime.Pinner
	defer __p.Unpin()
	if __err := wadge.WithCurrentInstance(func(__instance *wadge.Instance) error {
		return __instance.Call("wasi:http/types@0.2.0", "[method]fields.clone", func() unsafe.Pointer {
			ptr := unsafe.Pointer(&self0)
			__p.Pin(ptr)
			return ptr
		}(), func() unsafe.Pointer {
			ptr := unsafe.Pointer(&result0)
			__p.Pin(ptr)
			return ptr
		}())
	}); __err != nil {
		wadge.CurrentErrorHandler()(__err)
	}
	return
}

//go:linkname wasmimport_FieldsDelete github.com/wasmCloud/wadge/examples/go/http/bindings/wasi/http/types.wasmimport_FieldsDelete
func wasmimport_FieldsDelete(self0 uint32, name0 *uint8, name1 uint32, result *github_com__bytecodealliance__wasm___tools___go__cm.Result[github_com__wasmCloud__wadge__examples__go__http__bindings__wasi__http__types.HeaderError, struct{}, github_com__wasmCloud__wadge__examples__go__http__bindings__wasi__http__types.HeaderError]) {
	var __p runtime.Pinner
	defer __p.Unpin()
	if __err := wadge.WithCurrentInstance(func(__instance *wadge.Instance) error {
		return __instance.Call("wasi:http/types@0.2.0", "[method]fields.delete", func() unsafe.Pointer {
			ptr := unsafe.Pointer(&self0)
			__p.Pin(ptr)
			return ptr
		}(), func() unsafe.Pointer {
			ptr := unsafe.Pointer(name0)
			__p.Pin(ptr)
			return ptr
		}(), func() unsafe.Pointer {
			ptr := unsafe.Pointer(&name1)
			__p.Pin(ptr)
			return ptr
		}(), func() unsafe.Pointer {
			ptr := unsafe.Pointer(result)
			__p.Pin(ptr)
			return ptr
		}())
	}); __err != nil {
		wadge.CurrentErrorHandler()(__err)
	}
	return
}

//go:linkname wasmimport_FieldsEntries github.com/wasmCloud/wadge/examples/go/http/bindings/wasi/http/types.wasmimport_FieldsEntries
func wasmimport_FieldsEntries(self0 uint32, result *github_com__bytecodealliance__wasm___tools___go__cm.List[github_com__bytecodealliance__wasm___tools___go__cm.Tuple[github_com__wasmCloud__wadge__examples__go__http__bindings__wasi__http__types.FieldKey, github_com__wasmCloud__wadge__examples__go__http__bindings__wasi__http__types.FieldValue]]) {
	var __p runtime.Pinner
	defer __p.Unpin()
	if __err := wadge.WithCurrentInstance(func(__instance *wadge.Instance) error {
		return __instance.Call("wasi:http/types@0.2.0", "[method]fields.entries", func() unsafe.Pointer {
			ptr := unsafe.Pointer(&self0)
			__p.Pin(ptr)
			return ptr
		}(), func() unsafe.Pointer {
			ptr := unsafe.Pointer(result)
			__p.Pin(ptr)
			return ptr
		}())
	}); __err != nil {
		wadge.CurrentErrorHandler()(__err)
	}
	return
}

//go:linkname wasmimport_FieldsGet github.com/wasmCloud/wadge/examples/go/http/bindings/wasi/http/types.wasmimport_FieldsGet
func wasmimport_FieldsGet(self0 uint32, name0 *uint8, name1 uint32, result *github_com__bytecodealliance__wasm___tools___go__cm.List[github_com__wasmCloud__wadge__examples__go__http__bindings__wasi__http__types.FieldValue]) {
	var __p runtime.Pinner
	defer __p.Unpin()
	if __err := wadge.WithCurrentInstance(func(__instance *wadge.Instance) error {
		return __instance.Call("wasi:http/types@0.2.0", "[method]fields.get", func() unsafe.Pointer {
			ptr := unsafe.Pointer(&self0)
			__p.Pin(ptr)
			return ptr
		}(), func() unsafe.Pointer {
			ptr := unsafe.Pointer(name0)
			__p.Pin(ptr)
			return ptr
		}(), func() unsafe.Pointer {
			ptr := unsafe.Pointer(&name1)
			__p.Pin(ptr)
			return ptr
		}(), func() unsafe.Pointer {
			ptr := unsafe.Pointer(result)
			__p.Pin(ptr)
			return ptr
		}())
	}); __err != nil {
		wadge.CurrentErrorHandler()(__err)
	}
	return
}

//go:linkname wasmimport_FieldsHas github.com/wasmCloud/wadge/examples/go/http/bindings/wasi/http/types.wasmimport_FieldsHas
func wasmimport_FieldsHas(self0 uint32, name0 *uint8, name1 uint32) (result0 uint32) {
	var __p runtime.Pinner
	defer __p.Unpin()
	if __err := wadge.WithCurrentInstance(func(__instance *wadge.Instance) error {
		return __instance.Call("wasi:http/types@0.2.0", "[method]fields.has", func() unsafe.Pointer {
			ptr := unsafe.Pointer(&self0)
			__p.Pin(ptr)
			return ptr
		}(), func() unsafe.Pointer {
			ptr := unsafe.Pointer(name0)
			__p.Pin(ptr)
			return ptr
		}(), func() unsafe.Pointer {
			ptr := unsafe.Pointer(&name1)
			__p.Pin(ptr)
			return ptr
		}(), func() unsafe.Pointer {
			ptr := unsafe.Pointer(&result0)
			__p.Pin(ptr)
			return ptr
		}())
	}); __err != nil {
		wadge.CurrentErrorHandler()(__err)
	}
	return
}

//go:linkname wasmimport_FieldsSet github.com/wasmCloud/wadge/examples/go/http/bindings/wasi/http/types.wasmimport_FieldsSet
func wasmimport_FieldsSet(self0 uint32, name0 *uint8, name1 uint32, value0 *github_com__wasmCloud__wadge__examples__go__http__bindings__wasi__http__types.FieldValue, value1 uint32, result *github_com__bytecodealliance__wasm___tools___go__cm.Result[github_com__wasmCloud__wadge__examples__go__http__bindings__wasi__http__types.HeaderError, struct{}, github_com__wasmCloud__wadge__examples__go__http__bindings__wasi__http__types.HeaderError]) {
	var __p runtime.Pinner
	defer __p.Unpin()
	if __err := wadge.WithCurrentInstance(func(__instance *wadge.Instance) error {
		return __instance.Call("wasi:http/types@0.2.0", "[method]fields.set", func() unsafe.Pointer {
			ptr := unsafe.Pointer(&self0)
			__p.Pin(ptr)
			return ptr
		}(), func() unsafe.Pointer {
			ptr := unsafe.Pointer(name0)
			__p.Pin(ptr)
			return ptr
		}(), func() unsafe.Pointer {
			ptr := unsafe.Pointer(&name1)
			__p.Pin(ptr)
			return ptr
		}(), func() unsafe.Pointer {
			ptr := unsafe.Pointer(value0)
			__p.Pin(ptr)
			return ptr
		}(), func() unsafe.Pointer {
			ptr := unsafe.Pointer(&value1)
			__p.Pin(ptr)
			return ptr
		}(), func() unsafe.Pointer {
			ptr := unsafe.Pointer(result)
			__p.Pin(ptr)
			return ptr
		}())
	}); __err != nil {
		wadge.CurrentErrorHandler()(__err)
	}
	return
}

//go:linkname wasmimport_FutureIncomingResponseGet github.com/wasmCloud/wadge/examples/go/http/bindings/wasi/http/types.wasmimport_FutureIncomingResponseGet
func wasmimport_FutureIncomingResponseGet(self0 uint32, result *github_com__bytecodealliance__wasm___tools___go__cm.Option[github_com__bytecodealliance__wasm___tools___go__cm.Result[github_com__bytecodealliance__wasm___tools___go__cm.Result[github_com__wasmCloud__wadge__examples__go__http__bindings__wasi__http__types.ErrorCodeShape, github_com__wasmCloud__wadge__examples__go__http__bindings__wasi__http__types.IncomingResponse, github_com__wasmCloud__wadge__examples__go__http__bindings__wasi__http__types.ErrorCode], github_com__bytecodealliance__wasm___tools___go__cm.Result[github_com__wasmCloud__wadge__examples__go__http__bindings__wasi__http__types.ErrorCodeShape, github_com__wasmCloud__wadge__examples__go__http__bindings__wasi__http__types.IncomingResponse, github_com__wasmCloud__wadge__examples__go__http__bindings__wasi__http__types.ErrorCode], struct{}]]) {
	var __p runtime.Pinner
	defer __p.Unpin()
	if __err := wadge.WithCurrentInstance(func(__instance *wadge.Instance) error {
		return __instance.Call("wasi:http/types@0.2.0", "[method]future-incoming-response.get", func() unsafe.Pointer {
			ptr := unsafe.Pointer(&self0)
			__p.Pin(ptr)
			return ptr
		}(), func() unsafe.Pointer {
			ptr := unsafe.Pointer(result)
			__p.Pin(ptr)
			return ptr
		}())
	}); __err != nil {
		wadge.CurrentErrorHandler()(__err)
	}
	return
}

//go:linkname wasmimport_FutureIncomingResponseSubscribe github.com/wasmCloud/wadge/examples/go/http/bindings/wasi/http/types.wasmimport_FutureIncomingResponseSubscribe
func wasmimport_FutureIncomingResponseSubscribe(self0 uint32) (result0 uint32) {
	var __p runtime.Pinner
	defer __p.Unpin()
	if __err := wadge.WithCurrentInstance(func(__instance *wadge.Instance) error {
		return __instance.Call("wasi:http/types@0.2.0", "[method]future-incoming-response.subscribe", func() unsafe.Pointer {
			ptr := unsafe.Pointer(&self0)
			__p.Pin(ptr)
			return ptr
		}(), func() unsafe.Pointer {
			ptr := unsafe.Pointer(&result0)
			__p.Pin(ptr)
			return ptr
		}())
	}); __err != nil {
		wadge.CurrentErrorHandler()(__err)
	}
	return
}

//go:linkname wasmimport_FutureTrailersGet github.com/wasmCloud/wadge/examples/go/http/bindings/wasi/http/types.wasmimport_FutureTrailersGet
func wasmimport_FutureTrailersGet(self0 uint32, result *github_com__bytecodealliance__wasm___tools___go__cm.Option[github_com__bytecodealliance__wasm___tools___go__cm.Result[github_com__bytecodealliance__wasm___tools___go__cm.Result[github_com__wasmCloud__wadge__examples__go__http__bindings__wasi__http__types.ErrorCodeShape, github_com__bytecodealliance__wasm___tools___go__cm.Option[github_com__wasmCloud__wadge__examples__go__http__bindings__wasi__http__types.Fields], github_com__wasmCloud__wadge__examples__go__http__bindings__wasi__http__types.ErrorCode], github_com__bytecodealliance__wasm___tools___go__cm.Result[github_com__wasmCloud__wadge__examples__go__http__bindings__wasi__http__types.ErrorCodeShape, github_com__bytecodealliance__wasm___tools___go__cm.Option[github_com__wasmCloud__wadge__examples__go__http__bindings__wasi__http__types.Fields], github_com__wasmCloud__wadge__examples__go__http__bindings__wasi__http__types.ErrorCode], struct{}]]) {
	var __p runtime.Pinner
	defer __p.Unpin()
	if __err := wadge.WithCurrentInstance(func(__instance *wadge.Instance) error {
		return __instance.Call("wasi:http/types@0.2.0", "[method]future-trailers.get", func() unsafe.Pointer {
			ptr := unsafe.Pointer(&self0)
			__p.Pin(ptr)
			return ptr
		}(), func() unsafe.Pointer {
			ptr := unsafe.Pointer(result)
			__p.Pin(ptr)
			return ptr
		}())
	}); __err != nil {
		wadge.CurrentErrorHandler()(__err)
	}
	return
}

//go:linkname wasmimport_FutureTrailersSubscribe github.com/wasmCloud/wadge/examples/go/http/bindings/wasi/http/types.wasmimport_FutureTrailersSubscribe
func wasmimport_FutureTrailersSubscribe(self0 uint32) (result0 uint32) {
	var __p runtime.Pinner
	defer __p.Unpin()
	if __err := wadge.WithCurrentInstance(func(__instance *wadge.Instance) error {
		return __instance.Call("wasi:http/types@0.2.0", "[method]future-trailers.subscribe", func() unsafe.Pointer {
			ptr := unsafe.Pointer(&self0)
			__p.Pin(ptr)
			return ptr
		}(), func() unsafe.Pointer {
			ptr := unsafe.Pointer(&result0)
			__p.Pin(ptr)
			return ptr
		}())
	}); __err != nil {
		wadge.CurrentErrorHandler()(__err)
	}
	return
}

//go:linkname wasmimport_IncomingBodyStream github.com/wasmCloud/wadge/examples/go/http/bindings/wasi/http/types.wasmimport_IncomingBodyStream
func wasmimport_IncomingBodyStream(self0 uint32, result *github_com__bytecodealliance__wasm___tools___go__cm.Result[github_com__wasmCloud__wadge__examples__go__http__bindings__wasi__io__streams.InputStream, github_com__wasmCloud__wadge__examples__go__http__bindings__wasi__io__streams.InputStream, struct{}]) {
	var __p runtime.Pinner
	defer __p.Unpin()
	if __err := wadge.WithCurrentInstance(func(__instance *wadge.Instance) error {
		return __instance.Call("wasi:http/types@0.2.0", "[method]incoming-body.stream", func() unsafe.Pointer {
			ptr := unsafe.Pointer(&self0)
			__p.Pin(ptr)
			return ptr
		}(), func() unsafe.Pointer {
			ptr := unsafe.Pointer(result)
			__p.Pin(ptr)
			return ptr
		}())
	}); __err != nil {
		wadge.CurrentErrorHandler()(__err)
	}
	return
}

//go:linkname wasmimport_IncomingRequestAuthority github.com/wasmCloud/wadge/examples/go/http/bindings/wasi/http/types.wasmimport_IncomingRequestAuthority
func wasmimport_IncomingRequestAuthority(self0 uint32, result *github_com__bytecodealliance__wasm___tools___go__cm.Option[string]) {
	var __p runtime.Pinner
	defer __p.Unpin()
	if __err := wadge.WithCurrentInstance(func(__instance *wadge.Instance) error {
		return __instance.Call("wasi:http/types@0.2.0", "[method]incoming-request.authority", func() unsafe.Pointer {
			ptr := unsafe.Pointer(&self0)
			__p.Pin(ptr)
			return ptr
		}(), func() unsafe.Pointer {
			ptr := unsafe.Pointer(result)
			__p.Pin(ptr)
			return ptr
		}())
	}); __err != nil {
		wadge.CurrentErrorHandler()(__err)
	}
	return
}

//go:linkname wasmimport_IncomingRequestConsume github.com/wasmCloud/wadge/examples/go/http/bindings/wasi/http/types.wasmimport_IncomingRequestConsume
func wasmimport_IncomingRequestConsume(self0 uint32, result *github_com__bytecodealliance__wasm___tools___go__cm.Result[github_com__wasmCloud__wadge__examples__go__http__bindings__wasi__http__types.IncomingBody, github_com__wasmCloud__wadge__examples__go__http__bindings__wasi__http__types.IncomingBody, struct{}]) {
	var __p runtime.Pinner
	defer __p.Unpin()
	if __err := wadge.WithCurrentInstance(func(__instance *wadge.Instance) error {
		return __instance.Call("wasi:http/types@0.2.0", "[method]incoming-request.consume", func() unsafe.Pointer {
			ptr := unsafe.Pointer(&self0)
			__p.Pin(ptr)
			return ptr
		}(), func() unsafe.Pointer {
			ptr := unsafe.Pointer(result)
			__p.Pin(ptr)
			return ptr
		}())
	}); __err != nil {
		wadge.CurrentErrorHandler()(__err)
	}
	return
}

//go:linkname wasmimport_IncomingRequestHeaders github.com/wasmCloud/wadge/examples/go/http/bindings/wasi/http/types.wasmimport_IncomingRequestHeaders
func wasmimport_IncomingRequestHeaders(self0 uint32) (result0 uint32) {
	var __p runtime.Pinner
	defer __p.Unpin()
	if __err := wadge.WithCurrentInstance(func(__instance *wadge.Instance) error {
		return __instance.Call("wasi:http/types@0.2.0", "[method]incoming-request.headers", func() unsafe.Pointer {
			ptr := unsafe.Pointer(&self0)
			__p.Pin(ptr)
			return ptr
		}(), func() unsafe.Pointer {
			ptr := unsafe.Pointer(&result0)
			__p.Pin(ptr)
			return ptr
		}())
	}); __err != nil {
		wadge.CurrentErrorHandler()(__err)
	}
	return
}

//go:linkname wasmimport_IncomingRequestMethod github.com/wasmCloud/wadge/examples/go/http/bindings/wasi/http/types.wasmimport_IncomingRequestMethod
func wasmimport_IncomingRequestMethod(self0 uint32, result *github_com__wasmCloud__wadge__examples__go__http__bindings__wasi__http__types.Method) {
	var __p runtime.Pinner
	defer __p.Unpin()
	if __err := wadge.WithCurrentInstance(func(__instance *wadge.Instance) error {
		return __instance.Call("wasi:http/types@0.2.0", "[method]incoming-request.method", func() unsafe.Pointer {
			ptr := unsafe.Pointer(&self0)
			__p.Pin(ptr)
			return ptr
		}(), func() unsafe.Pointer {
			ptr := unsafe.Pointer(result)
			__p.Pin(ptr)
			return ptr
		}())
	}); __err != nil {
		wadge.CurrentErrorHandler()(__err)
	}
	return
}

//go:linkname wasmimport_IncomingRequestPathWithQuery github.com/wasmCloud/wadge/examples/go/http/bindings/wasi/http/types.wasmimport_IncomingRequestPathWithQuery
func wasmimport_IncomingRequestPathWithQuery(self0 uint32, result *github_com__bytecodealliance__wasm___tools___go__cm.Option[string]) {
	var __p runtime.Pinner
	defer __p.Unpin()
	if __err := wadge.WithCurrentInstance(func(__instance *wadge.Instance) error {
		return __instance.Call("wasi:http/types@0.2.0", "[method]incoming-request.path-with-query", func() unsafe.Pointer {
			ptr := unsafe.Pointer(&self0)
			__p.Pin(ptr)
			return ptr
		}(), func() unsafe.Pointer {
			ptr := unsafe.Pointer(result)
			__p.Pin(ptr)
			return ptr
		}())
	}); __err != nil {
		wadge.CurrentErrorHandler()(__err)
	}
	return
}

//go:linkname wasmimport_IncomingRequestScheme github.com/wasmCloud/wadge/examples/go/http/bindings/wasi/http/types.wasmimport_IncomingRequestScheme
func wasmimport_IncomingRequestScheme(self0 uint32, result *github_com__bytecodealliance__wasm___tools___go__cm.Option[github_com__wasmCloud__wadge__examples__go__http__bindings__wasi__http__types.Scheme]) {
	var __p runtime.Pinner
	defer __p.Unpin()
	if __err := wadge.WithCurrentInstance(func(__instance *wadge.Instance) error {
		return __instance.Call("wasi:http/types@0.2.0", "[method]incoming-request.scheme", func() unsafe.Pointer {
			ptr := unsafe.Pointer(&self0)
			__p.Pin(ptr)
			return ptr
		}(), func() unsafe.Pointer {
			ptr := unsafe.Pointer(result)
			__p.Pin(ptr)
			return ptr
		}())
	}); __err != nil {
		wadge.CurrentErrorHandler()(__err)
	}
	return
}

//go:linkname wasmimport_IncomingResponseConsume github.com/wasmCloud/wadge/examples/go/http/bindings/wasi/http/types.wasmimport_IncomingResponseConsume
func wasmimport_IncomingResponseConsume(self0 uint32, result *github_com__bytecodealliance__wasm___tools___go__cm.Result[github_com__wasmCloud__wadge__examples__go__http__bindings__wasi__http__types.IncomingBody, github_com__wasmCloud__wadge__examples__go__http__bindings__wasi__http__types.IncomingBody, struct{}]) {
	var __p runtime.Pinner
	defer __p.Unpin()
	if __err := wadge.WithCurrentInstance(func(__instance *wadge.Instance) error {
		return __instance.Call("wasi:http/types@0.2.0", "[method]incoming-response.consume", func() unsafe.Pointer {
			ptr := unsafe.Pointer(&self0)
			__p.Pin(ptr)
			return ptr
		}(), func() unsafe.Pointer {
			ptr := unsafe.Pointer(result)
			__p.Pin(ptr)
			return ptr
		}())
	}); __err != nil {
		wadge.CurrentErrorHandler()(__err)
	}
	return
}

//go:linkname wasmimport_IncomingResponseHeaders github.com/wasmCloud/wadge/examples/go/http/bindings/wasi/http/types.wasmimport_IncomingResponseHeaders
func wasmimport_IncomingResponseHeaders(self0 uint32) (result0 uint32) {
	var __p runtime.Pinner
	defer __p.Unpin()
	if __err := wadge.WithCurrentInstance(func(__instance *wadge.Instance) error {
		return __instance.Call("wasi:http/types@0.2.0", "[method]incoming-response.headers", func() unsafe.Pointer {
			ptr := unsafe.Pointer(&self0)
			__p.Pin(ptr)
			return ptr
		}(), func() unsafe.Pointer {
			ptr := unsafe.Pointer(&result0)
			__p.Pin(ptr)
			return ptr
		}())
	}); __err != nil {
		wadge.CurrentErrorHandler()(__err)
	}
	return
}

//go:linkname wasmimport_IncomingResponseStatus github.com/wasmCloud/wadge/examples/go/http/bindings/wasi/http/types.wasmimport_IncomingResponseStatus
func wasmimport_IncomingResponseStatus(self0 uint32) (result0 uint32) {
	var __p runtime.Pinner
	defer __p.Unpin()
	if __err := wadge.WithCurrentInstance(func(__instance *wadge.Instance) error {
		return __instance.Call("wasi:http/types@0.2.0", "[method]incoming-response.status", func() unsafe.Pointer {
			ptr := unsafe.Pointer(&self0)
			__p.Pin(ptr)
			return ptr
		}(), func() unsafe.Pointer {
			ptr := unsafe.Pointer(&result0)
			__p.Pin(ptr)
			return ptr
		}())
	}); __err != nil {
		wadge.CurrentErrorHandler()(__err)
	}
	return
}

//go:linkname wasmimport_OutgoingBodyWrite github.com/wasmCloud/wadge/examples/go/http/bindings/wasi/http/types.wasmimport_OutgoingBodyWrite
func wasmimport_OutgoingBodyWrite(self0 uint32, result *github_com__bytecodealliance__wasm___tools___go__cm.Result[github_com__wasmCloud__wadge__examples__go__http__bindings__wasi__io__streams.OutputStream, github_com__wasmCloud__wadge__examples__go__http__bindings__wasi__io__streams.OutputStream, struct{}]) {
	var __p runtime.Pinner
	defer __p.Unpin()
	if __err := wadge.WithCurrentInstance(func(__instance *wadge.Instance) error {
		return __instance.Call("wasi:http/types@0.2.0", "[method]outgoing-body.write", func() unsafe.Pointer {
			ptr := unsafe.Pointer(&self0)
			__p.Pin(ptr)
			return ptr
		}(), func() unsafe.Pointer {
			ptr := unsafe.Pointer(result)
			__p.Pin(ptr)
			return ptr
		}())
	}); __err != nil {
		wadge.CurrentErrorHandler()(__err)
	}
	return
}

//go:linkname wasmimport_OutgoingRequestAuthority github.com/wasmCloud/wadge/examples/go/http/bindings/wasi/http/types.wasmimport_OutgoingRequestAuthority
func wasmimport_OutgoingRequestAuthority(self0 uint32, result *github_com__bytecodealliance__wasm___tools___go__cm.Option[string]) {
	var __p runtime.Pinner
	defer __p.Unpin()
	if __err := wadge.WithCurrentInstance(func(__instance *wadge.Instance) error {
		return __instance.Call("wasi:http/types@0.2.0", "[method]outgoing-request.authority", func() unsafe.Pointer {
			ptr := unsafe.Pointer(&self0)
			__p.Pin(ptr)
			return ptr
		}(), func() unsafe.Pointer {
			ptr := unsafe.Pointer(result)
			__p.Pin(ptr)
			return ptr
		}())
	}); __err != nil {
		wadge.CurrentErrorHandler()(__err)
	}
	return
}

//go:linkname wasmimport_OutgoingRequestBody github.com/wasmCloud/wadge/examples/go/http/bindings/wasi/http/types.wasmimport_OutgoingRequestBody
func wasmimport_OutgoingRequestBody(self0 uint32, result *github_com__bytecodealliance__wasm___tools___go__cm.Result[github_com__wasmCloud__wadge__examples__go__http__bindings__wasi__http__types.OutgoingBody, github_com__wasmCloud__wadge__examples__go__http__bindings__wasi__http__types.OutgoingBody, struct{}]) {
	var __p runtime.Pinner
	defer __p.Unpin()
	if __err := wadge.WithCurrentInstance(func(__instance *wadge.Instance) error {
		return __instance.Call("wasi:http/types@0.2.0", "[method]outgoing-request.body", func() unsafe.Pointer {
			ptr := unsafe.Pointer(&self0)
			__p.Pin(ptr)
			return ptr
		}(), func() unsafe.Pointer {
			ptr := unsafe.Pointer(result)
			__p.Pin(ptr)
			return ptr
		}())
	}); __err != nil {
		wadge.CurrentErrorHandler()(__err)
	}
	return
}

//go:linkname wasmimport_OutgoingRequestHeaders github.com/wasmCloud/wadge/examples/go/http/bindings/wasi/http/types.wasmimport_OutgoingRequestHeaders
func wasmimport_OutgoingRequestHeaders(self0 uint32) (result0 uint32) {
	var __p runtime.Pinner
	defer __p.Unpin()
	if __err := wadge.WithCurrentInstance(func(__instance *wadge.Instance) error {
		return __instance.Call("wasi:http/types@0.2.0", "[method]outgoing-request.headers", func() unsafe.Pointer {
			ptr := unsafe.Pointer(&self0)
			__p.Pin(ptr)
			return ptr
		}(), func() unsafe.Pointer {
			ptr := unsafe.Pointer(&result0)
			__p.Pin(ptr)
			return ptr
		}())
	}); __err != nil {
		wadge.CurrentErrorHandler()(__err)
	}
	return
}

//go:linkname wasmimport_OutgoingRequestMethod github.com/wasmCloud/wadge/examples/go/http/bindings/wasi/http/types.wasmimport_OutgoingRequestMethod
func wasmimport_OutgoingRequestMethod(self0 uint32, result *github_com__wasmCloud__wadge__examples__go__http__bindings__wasi__http__types.Method) {
	var __p runtime.Pinner
	defer __p.Unpin()
	if __err := wadge.WithCurrentInstance(func(__instance *wadge.Instance) error {
		return __instance.Call("wasi:http/types@0.2.0", "[method]outgoing-request.method", func() unsafe.Pointer {
			ptr := unsafe.Pointer(&self0)
			__p.Pin(ptr)
			return ptr
		}(), func() unsafe.Pointer {
			ptr := unsafe.Pointer(result)
			__p.Pin(ptr)
			return ptr
		}())
	}); __err != nil {
		wadge.CurrentErrorHandler()(__err)
	}
	return
}

//go:linkname wasmimport_OutgoingRequestPathWithQuery github.com/wasmCloud/wadge/examples/go/http/bindings/wasi/http/types.wasmimport_OutgoingRequestPathWithQuery
func wasmimport_OutgoingRequestPathWithQuery(self0 uint32, result *github_com__bytecodealliance__wasm___tools___go__cm.Option[string]) {
	var __p runtime.Pinner
	defer __p.Unpin()
	if __err := wadge.WithCurrentInstance(func(__instance *wadge.Instance) error {
		return __instance.Call("wasi:http/types@0.2.0", "[method]outgoing-request.path-with-query", func() unsafe.Pointer {
			ptr := unsafe.Pointer(&self0)
			__p.Pin(ptr)
			return ptr
		}(), func() unsafe.Pointer {
			ptr := unsafe.Pointer(result)
			__p.Pin(ptr)
			return ptr
		}())
	}); __err != nil {
		wadge.CurrentErrorHandler()(__err)
	}
	return
}

//go:linkname wasmimport_OutgoingRequestScheme github.com/wasmCloud/wadge/examples/go/http/bindings/wasi/http/types.wasmimport_OutgoingRequestScheme
func wasmimport_OutgoingRequestScheme(self0 uint32, result *github_com__bytecodealliance__wasm___tools___go__cm.Option[github_com__wasmCloud__wadge__examples__go__http__bindings__wasi__http__types.Scheme]) {
	var __p runtime.Pinner
	defer __p.Unpin()
	if __err := wadge.WithCurrentInstance(func(__instance *wadge.Instance) error {
		return __instance.Call("wasi:http/types@0.2.0", "[method]outgoing-request.scheme", func() unsafe.Pointer {
			ptr := unsafe.Pointer(&self0)
			__p.Pin(ptr)
			return ptr
		}(), func() unsafe.Pointer {
			ptr := unsafe.Pointer(result)
			__p.Pin(ptr)
			return ptr
		}())
	}); __err != nil {
		wadge.CurrentErrorHandler()(__err)
	}
	return
}

//go:linkname wasmimport_OutgoingRequestSetAuthority github.com/wasmCloud/wadge/examples/go/http/bindings/wasi/http/types.wasmimport_OutgoingRequestSetAuthority
func wasmimport_OutgoingRequestSetAuthority(self0 uint32, authority0 uint32, authority1 *uint8, authority2 uint32) (result0 uint32) {
	var __p runtime.Pinner
	defer __p.Unpin()
	if __err := wadge.WithCurrentInstance(func(__instance *wadge.Instance) error {
		return __instance.Call("wasi:http/types@0.2.0", "[method]outgoing-request.set-authority", func() unsafe.Pointer {
			ptr := unsafe.Pointer(&self0)
			__p.Pin(ptr)
			return ptr
		}(), func() unsafe.Pointer {
			ptr := unsafe.Pointer(&authority0)
			__p.Pin(ptr)
			return ptr
		}(), func() unsafe.Pointer {
			ptr := unsafe.Pointer(authority1)
			__p.Pin(ptr)
			return ptr
		}(), func() unsafe.Pointer {
			ptr := unsafe.Pointer(&authority2)
			__p.Pin(ptr)
			return ptr
		}(), func() unsafe.Pointer {
			ptr := unsafe.Pointer(&result0)
			__p.Pin(ptr)
			return ptr
		}())
	}); __err != nil {
		wadge.CurrentErrorHandler()(__err)
	}
	return
}

//go:linkname wasmimport_OutgoingRequestSetMethod github.com/wasmCloud/wadge/examples/go/http/bindings/wasi/http/types.wasmimport_OutgoingRequestSetMethod
func wasmimport_OutgoingRequestSetMethod(self0 uint32, method0 uint32, method1 *uint8, method2 uint32) (result0 uint32) {
	var __p runtime.Pinner
	defer __p.Unpin()
	if __err := wadge.WithCurrentInstance(func(__instance *wadge.Instance) error {
		return __instance.Call("wasi:http/types@0.2.0", "[method]outgoing-request.set-method", func() unsafe.Pointer {
			ptr := unsafe.Pointer(&self0)
			__p.Pin(ptr)
			return ptr
		}(), func() unsafe.Pointer {
			ptr := unsafe.Pointer(&method0)
			__p.Pin(ptr)
			return ptr
		}(), func() unsafe.Pointer {
			ptr := unsafe.Pointer(method1)
			__p.Pin(ptr)
			return ptr
		}(), func() unsafe.Pointer {
			ptr := unsafe.Pointer(&method2)
			__p.Pin(ptr)
			return ptr
		}(), func() unsafe.Pointer {
			ptr := unsafe.Pointer(&result0)
			__p.Pin(ptr)
			return ptr
		}())
	}); __err != nil {
		wadge.CurrentErrorHandler()(__err)
	}
	return
}

//go:linkname wasmimport_OutgoingRequestSetPathWithQuery github.com/wasmCloud/wadge/examples/go/http/bindings/wasi/http/types.wasmimport_OutgoingRequestSetPathWithQuery
func wasmimport_OutgoingRequestSetPathWithQuery(self0 uint32, pathWithQuery0 uint32, pathWithQuery1 *uint8, pathWithQuery2 uint32) (result0 uint32) {
	var __p runtime.Pinner
	defer __p.Unpin()
	if __err := wadge.WithCurrentInstance(func(__instance *wadge.Instance) error {
		return __instance.Call("wasi:http/types@0.2.0", "[method]outgoing-request.set-path-with-query", func() unsafe.Pointer {
			ptr := unsafe.Pointer(&self0)
			__p.Pin(ptr)
			return ptr
		}(), func() unsafe.Pointer {
			ptr := unsafe.Pointer(&pathWithQuery0)
			__p.Pin(ptr)
			return ptr
		}(), func() unsafe.Pointer {
			ptr := unsafe.Pointer(pathWithQuery1)
			__p.Pin(ptr)
			return ptr
		}(), func() unsafe.Pointer {
			ptr := unsafe.Pointer(&pathWithQuery2)
			__p.Pin(ptr)
			return ptr
		}(), func() unsafe.Pointer {
			ptr := unsafe.Pointer(&result0)
			__p.Pin(ptr)
			return ptr
		}())
	}); __err != nil {
		wadge.CurrentErrorHandler()(__err)
	}
	return
}

//go:linkname wasmimport_OutgoingRequestSetScheme github.com/wasmCloud/wadge/examples/go/http/bindings/wasi/http/types.wasmimport_OutgoingRequestSetScheme
func wasmimport_OutgoingRequestSetScheme(self0 uint32, scheme0 uint32, scheme1 uint32, scheme2 *uint8, scheme3 uint32) (result0 uint32) {
	var __p runtime.Pinner
	defer __p.Unpin()
	if __err := wadge.WithCurrentInstance(func(__instance *wadge.Instance) error {
		return __instance.Call("wasi:http/types@0.2.0", "[method]outgoing-request.set-scheme", func() unsafe.Pointer {
			ptr := unsafe.Pointer(&self0)
			__p.Pin(ptr)
			return ptr
		}(), func() unsafe.Pointer {
			ptr := unsafe.Pointer(&scheme0)
			__p.Pin(ptr)
			return ptr
		}(), func() unsafe.Pointer {
			ptr := unsafe.Pointer(&scheme1)
			__p.Pin(ptr)
			return ptr
		}(), func() unsafe.Pointer {
			ptr := unsafe.Pointer(scheme2)
			__p.Pin(ptr)
			return ptr
		}(), func() unsafe.Pointer {
			ptr := unsafe.Pointer(&scheme3)
			__p.Pin(ptr)
			return ptr
		}(), func() unsafe.Pointer {
			ptr := unsafe.Pointer(&result0)
			__p.Pin(ptr)
			return ptr
		}())
	}); __err != nil {
		wadge.CurrentErrorHandler()(__err)
	}
	return
}

//go:linkname wasmimport_OutgoingResponseBody github.com/wasmCloud/wadge/examples/go/http/bindings/wasi/http/types.wasmimport_OutgoingResponseBody
func wasmimport_OutgoingResponseBody(self0 uint32, result *github_com__bytecodealliance__wasm___tools___go__cm.Result[github_com__wasmCloud__wadge__examples__go__http__bindings__wasi__http__types.OutgoingBody, github_com__wasmCloud__wadge__examples__go__http__bindings__wasi__http__types.OutgoingBody, struct{}]) {
	var __p runtime.Pinner
	defer __p.Unpin()
	if __err := wadge.WithCurrentInstance(func(__instance *wadge.Instance) error {
		return __instance.Call("wasi:http/types@0.2.0", "[method]outgoing-response.body", func() unsafe.Pointer {
			ptr := unsafe.Pointer(&self0)
			__p.Pin(ptr)
			return ptr
		}(), func() unsafe.Pointer {
			ptr := unsafe.Pointer(result)
			__p.Pin(ptr)
			return ptr
		}())
	}); __err != nil {
		wadge.CurrentErrorHandler()(__err)
	}
	return
}

//go:linkname wasmimport_OutgoingResponseHeaders github.com/wasmCloud/wadge/examples/go/http/bindings/wasi/http/types.wasmimport_OutgoingResponseHeaders
func wasmimport_OutgoingResponseHeaders(self0 uint32) (result0 uint32) {
	var __p runtime.Pinner
	defer __p.Unpin()
	if __err := wadge.WithCurrentInstance(func(__instance *wadge.Instance) error {
		return __instance.Call("wasi:http/types@0.2.0", "[method]outgoing-response.headers", func() unsafe.Pointer {
			ptr := unsafe.Pointer(&self0)
			__p.Pin(ptr)
			return ptr
		}(), func() unsafe.Pointer {
			ptr := unsafe.Pointer(&result0)
			__p.Pin(ptr)
			return ptr
		}())
	}); __err != nil {
		wadge.CurrentErrorHandler()(__err)
	}
	return
}

//go:linkname wasmimport_OutgoingResponseSetStatusCode github.com/wasmCloud/wadge/examples/go/http/bindings/wasi/http/types.wasmimport_OutgoingResponseSetStatusCode
func wasmimport_OutgoingResponseSetStatusCode(self0 uint32, statusCode0 uint32) (result0 uint32) {
	var __p runtime.Pinner
	defer __p.Unpin()
	if __err := wadge.WithCurrentInstance(func(__instance *wadge.Instance) error {
		return __instance.Call("wasi:http/types@0.2.0", "[method]outgoing-response.set-status-code", func() unsafe.Pointer {
			ptr := unsafe.Pointer(&self0)
			__p.Pin(ptr)
			return ptr
		}(), func() unsafe.Pointer {
			ptr := unsafe.Pointer(&statusCode0)
			__p.Pin(ptr)
			return ptr
		}(), func() unsafe.Pointer {
			ptr := unsafe.Pointer(&result0)
			__p.Pin(ptr)
			return ptr
		}())
	}); __err != nil {
		wadge.CurrentErrorHandler()(__err)
	}
	return
}

//go:linkname wasmimport_OutgoingResponseStatusCode github.com/wasmCloud/wadge/examples/go/http/bindings/wasi/http/types.wasmimport_OutgoingResponseStatusCode
func wasmimport_OutgoingResponseStatusCode(self0 uint32) (result0 uint32) {
	var __p runtime.Pinner
	defer __p.Unpin()
	if __err := wadge.WithCurrentInstance(func(__instance *wadge.Instance) error {
		return __instance.Call("wasi:http/types@0.2.0", "[method]outgoing-response.status-code", func() unsafe.Pointer {
			ptr := unsafe.Pointer(&self0)
			__p.Pin(ptr)
			return ptr
		}(), func() unsafe.Pointer {
			ptr := unsafe.Pointer(&result0)
			__p.Pin(ptr)
			return ptr
		}())
	}); __err != nil {
		wadge.CurrentErrorHandler()(__err)
	}
	return
}

//go:linkname wasmimport_RequestOptionsBetweenBytesTimeout github.com/wasmCloud/wadge/examples/go/http/bindings/wasi/http/types.wasmimport_RequestOptionsBetweenBytesTimeout
func wasmimport_RequestOptionsBetweenBytesTimeout(self0 uint32, result *github_com__bytecodealliance__wasm___tools___go__cm.Option[github_com__wasmCloud__wadge__examples__go__http__bindings__wasi__clocks__monotonic___clock.Duration]) {
	var __p runtime.Pinner
	defer __p.Unpin()
	if __err := wadge.WithCurrentInstance(func(__instance *wadge.Instance) error {
		return __instance.Call("wasi:http/types@0.2.0", "[method]request-options.between-bytes-timeout", func() unsafe.Pointer {
			ptr := unsafe.Pointer(&self0)
			__p.Pin(ptr)
			return ptr
		}(), func() unsafe.Pointer {
			ptr := unsafe.Pointer(result)
			__p.Pin(ptr)
			return ptr
		}())
	}); __err != nil {
		wadge.CurrentErrorHandler()(__err)
	}
	return
}

//go:linkname wasmimport_RequestOptionsConnectTimeout github.com/wasmCloud/wadge/examples/go/http/bindings/wasi/http/types.wasmimport_RequestOptionsConnectTimeout
func wasmimport_RequestOptionsConnectTimeout(self0 uint32, result *github_com__bytecodealliance__wasm___tools___go__cm.Option[github_com__wasmCloud__wadge__examples__go__http__bindings__wasi__clocks__monotonic___clock.Duration]) {
	var __p runtime.Pinner
	defer __p.Unpin()
	if __err := wadge.WithCurrentInstance(func(__instance *wadge.Instance) error {
		return __instance.Call("wasi:http/types@0.2.0", "[method]request-options.connect-timeout", func() unsafe.Pointer {
			ptr := unsafe.Pointer(&self0)
			__p.Pin(ptr)
			return ptr
		}(), func() unsafe.Pointer {
			ptr := unsafe.Pointer(result)
			__p.Pin(ptr)
			return ptr
		}())
	}); __err != nil {
		wadge.CurrentErrorHandler()(__err)
	}
	return
}

//go:linkname wasmimport_RequestOptionsFirstByteTimeout github.com/wasmCloud/wadge/examples/go/http/bindings/wasi/http/types.wasmimport_RequestOptionsFirstByteTimeout
func wasmimport_RequestOptionsFirstByteTimeout(self0 uint32, result *github_com__bytecodealliance__wasm___tools___go__cm.Option[github_com__wasmCloud__wadge__examples__go__http__bindings__wasi__clocks__monotonic___clock.Duration]) {
	var __p runtime.Pinner
	defer __p.Unpin()
	if __err := wadge.WithCurrentInstance(func(__instance *wadge.Instance) error {
		return __instance.Call("wasi:http/types@0.2.0", "[method]request-options.first-byte-timeout", func() unsafe.Pointer {
			ptr := unsafe.Pointer(&self0)
			__p.Pin(ptr)
			return ptr
		}(), func() unsafe.Pointer {
			ptr := unsafe.Pointer(result)
			__p.Pin(ptr)
			return ptr
		}())
	}); __err != nil {
		wadge.CurrentErrorHandler()(__err)
	}
	return
}

//go:linkname wasmimport_RequestOptionsSetBetweenBytesTimeout github.com/wasmCloud/wadge/examples/go/http/bindings/wasi/http/types.wasmimport_RequestOptionsSetBetweenBytesTimeout
func wasmimport_RequestOptionsSetBetweenBytesTimeout(self0 uint32, duration0 uint32, duration1 uint64) (result0 uint32) {
	var __p runtime.Pinner
	defer __p.Unpin()
	if __err := wadge.WithCurrentInstance(func(__instance *wadge.Instance) error {
		return __instance.Call("wasi:http/types@0.2.0", "[method]request-options.set-between-bytes-timeout", func() unsafe.Pointer {
			ptr := unsafe.Pointer(&self0)
			__p.Pin(ptr)
			return ptr
		}(), func() unsafe.Pointer {
			ptr := unsafe.Pointer(&duration0)
			__p.Pin(ptr)
			return ptr
		}(), func() unsafe.Pointer {
			ptr := unsafe.Pointer(&duration1)
			__p.Pin(ptr)
			return ptr
		}(), func() unsafe.Pointer {
			ptr := unsafe.Pointer(&result0)
			__p.Pin(ptr)
			return ptr
		}())
	}); __err != nil {
		wadge.CurrentErrorHandler()(__err)
	}
	return
}

//go:linkname wasmimport_RequestOptionsSetConnectTimeout github.com/wasmCloud/wadge/examples/go/http/bindings/wasi/http/types.wasmimport_RequestOptionsSetConnectTimeout
func wasmimport_RequestOptionsSetConnectTimeout(self0 uint32, duration0 uint32, duration1 uint64) (result0 uint32) {
	var __p runtime.Pinner
	defer __p.Unpin()
	if __err := wadge.WithCurrentInstance(func(__instance *wadge.Instance) error {
		return __instance.Call("wasi:http/types@0.2.0", "[method]request-options.set-connect-timeout", func() unsafe.Pointer {
			ptr := unsafe.Pointer(&self0)
			__p.Pin(ptr)
			return ptr
		}(), func() unsafe.Pointer {
			ptr := unsafe.Pointer(&duration0)
			__p.Pin(ptr)
			return ptr
		}(), func() unsafe.Pointer {
			ptr := unsafe.Pointer(&duration1)
			__p.Pin(ptr)
			return ptr
		}(), func() unsafe.Pointer {
			ptr := unsafe.Pointer(&result0)
			__p.Pin(ptr)
			return ptr
		}())
	}); __err != nil {
		wadge.CurrentErrorHandler()(__err)
	}
	return
}

//go:linkname wasmimport_RequestOptionsSetFirstByteTimeout github.com/wasmCloud/wadge/examples/go/http/bindings/wasi/http/types.wasmimport_RequestOptionsSetFirstByteTimeout
func wasmimport_RequestOptionsSetFirstByteTimeout(self0 uint32, duration0 uint32, duration1 uint64) (result0 uint32) {
	var __p runtime.Pinner
	defer __p.Unpin()
	if __err := wadge.WithCurrentInstance(func(__instance *wadge.Instance) error {
		return __instance.Call("wasi:http/types@0.2.0", "[method]request-options.set-first-byte-timeout", func() unsafe.Pointer {
			ptr := unsafe.Pointer(&self0)
			__p.Pin(ptr)
			return ptr
		}(), func() unsafe.Pointer {
			ptr := unsafe.Pointer(&duration0)
			__p.Pin(ptr)
			return ptr
		}(), func() unsafe.Pointer {
			ptr := unsafe.Pointer(&duration1)
			__p.Pin(ptr)
			return ptr
		}(), func() unsafe.Pointer {
			ptr := unsafe.Pointer(&result0)
			__p.Pin(ptr)
			return ptr
		}())
	}); __err != nil {
		wadge.CurrentErrorHandler()(__err)
	}
	return
}

//go:linkname wasmimport_FieldsResourceDrop github.com/wasmCloud/wadge/examples/go/http/bindings/wasi/http/types.wasmimport_FieldsResourceDrop
func wasmimport_FieldsResourceDrop(self0 uint32) {
	var __p runtime.Pinner
	defer __p.Unpin()
	if __err := wadge.WithCurrentInstance(func(__instance *wadge.Instance) error {
		return __instance.Call("wasi:http/types@0.2.0", "[resource-drop]fields", func() unsafe.Pointer {
			ptr := unsafe.Pointer(&self0)
			__p.Pin(ptr)
			return ptr
		}())
	}); __err != nil {
		wadge.CurrentErrorHandler()(__err)
	}
	return
}

//go:linkname wasmimport_FutureIncomingResponseResourceDrop github.com/wasmCloud/wadge/examples/go/http/bindings/wasi/http/types.wasmimport_FutureIncomingResponseResourceDrop
func wasmimport_FutureIncomingResponseResourceDrop(self0 uint32) {
	var __p runtime.Pinner
	defer __p.Unpin()
	if __err := wadge.WithCurrentInstance(func(__instance *wadge.Instance) error {
		return __instance.Call("wasi:http/types@0.2.0", "[resource-drop]future-incoming-response", func() unsafe.Pointer {
			ptr := unsafe.Pointer(&self0)
			__p.Pin(ptr)
			return ptr
		}())
	}); __err != nil {
		wadge.CurrentErrorHandler()(__err)
	}
	return
}

//go:linkname wasmimport_FutureTrailersResourceDrop github.com/wasmCloud/wadge/examples/go/http/bindings/wasi/http/types.wasmimport_FutureTrailersResourceDrop
func wasmimport_FutureTrailersResourceDrop(self0 uint32) {
	var __p runtime.Pinner
	defer __p.Unpin()
	if __err := wadge.WithCurrentInstance(func(__instance *wadge.Instance) error {
		return __instance.Call("wasi:http/types@0.2.0", "[resource-drop]future-trailers", func() unsafe.Pointer {
			ptr := unsafe.Pointer(&self0)
			__p.Pin(ptr)
			return ptr
		}())
	}); __err != nil {
		wadge.CurrentErrorHandler()(__err)
	}
	return
}

//go:linkname wasmimport_IncomingBodyResourceDrop github.com/wasmCloud/wadge/examples/go/http/bindings/wasi/http/types.wasmimport_IncomingBodyResourceDrop
func wasmimport_IncomingBodyResourceDrop(self0 uint32) {
	var __p runtime.Pinner
	defer __p.Unpin()
	if __err := wadge.WithCurrentInstance(func(__instance *wadge.Instance) error {
		return __instance.Call("wasi:http/types@0.2.0", "[resource-drop]incoming-body", func() unsafe.Pointer {
			ptr := unsafe.Pointer(&self0)
			__p.Pin(ptr)
			return ptr
		}())
	}); __err != nil {
		wadge.CurrentErrorHandler()(__err)
	}
	return
}

//go:linkname wasmimport_IncomingRequestResourceDrop github.com/wasmCloud/wadge/examples/go/http/bindings/wasi/http/types.wasmimport_IncomingRequestResourceDrop
func wasmimport_IncomingRequestResourceDrop(self0 uint32) {
	var __p runtime.Pinner
	defer __p.Unpin()
	if __err := wadge.WithCurrentInstance(func(__instance *wadge.Instance) error {
		return __instance.Call("wasi:http/types@0.2.0", "[resource-drop]incoming-request", func() unsafe.Pointer {
			ptr := unsafe.Pointer(&self0)
			__p.Pin(ptr)
			return ptr
		}())
	}); __err != nil {
		wadge.CurrentErrorHandler()(__err)
	}
	return
}

//go:linkname wasmimport_IncomingResponseResourceDrop github.com/wasmCloud/wadge/examples/go/http/bindings/wasi/http/types.wasmimport_IncomingResponseResourceDrop
func wasmimport_IncomingResponseResourceDrop(self0 uint32) {
	var __p runtime.Pinner
	defer __p.Unpin()
	if __err := wadge.WithCurrentInstance(func(__instance *wadge.Instance) error {
		return __instance.Call("wasi:http/types@0.2.0", "[resource-drop]incoming-response", func() unsafe.Pointer {
			ptr := unsafe.Pointer(&self0)
			__p.Pin(ptr)
			return ptr
		}())
	}); __err != nil {
		wadge.CurrentErrorHandler()(__err)
	}
	return
}

//go:linkname wasmimport_OutgoingBodyResourceDrop github.com/wasmCloud/wadge/examples/go/http/bindings/wasi/http/types.wasmimport_OutgoingBodyResourceDrop
func wasmimport_OutgoingBodyResourceDrop(self0 uint32) {
	var __p runtime.Pinner
	defer __p.Unpin()
	if __err := wadge.WithCurrentInstance(func(__instance *wadge.Instance) error {
		return __instance.Call("wasi:http/types@0.2.0", "[resource-drop]outgoing-body", func() unsafe.Pointer {
			ptr := unsafe.Pointer(&self0)
			__p.Pin(ptr)
			return ptr
		}())
	}); __err != nil {
		wadge.CurrentErrorHandler()(__err)
	}
	return
}

//go:linkname wasmimport_OutgoingRequestResourceDrop github.com/wasmCloud/wadge/examples/go/http/bindings/wasi/http/types.wasmimport_OutgoingRequestResourceDrop
func wasmimport_OutgoingRequestResourceDrop(self0 uint32) {
	var __p runtime.Pinner
	defer __p.Unpin()
	if __err := wadge.WithCurrentInstance(func(__instance *wadge.Instance) error {
		return __instance.Call("wasi:http/types@0.2.0", "[resource-drop]outgoing-request", func() unsafe.Pointer {
			ptr := unsafe.Pointer(&self0)
			__p.Pin(ptr)
			return ptr
		}())
	}); __err != nil {
		wadge.CurrentErrorHandler()(__err)
	}
	return
}

//go:linkname wasmimport_OutgoingResponseResourceDrop github.com/wasmCloud/wadge/examples/go/http/bindings/wasi/http/types.wasmimport_OutgoingResponseResourceDrop
func wasmimport_OutgoingResponseResourceDrop(self0 uint32) {
	var __p runtime.Pinner
	defer __p.Unpin()
	if __err := wadge.WithCurrentInstance(func(__instance *wadge.Instance) error {
		return __instance.Call("wasi:http/types@0.2.0", "[resource-drop]outgoing-response", func() unsafe.Pointer {
			ptr := unsafe.Pointer(&self0)
			__p.Pin(ptr)
			return ptr
		}())
	}); __err != nil {
		wadge.CurrentErrorHandler()(__err)
	}
	return
}

//go:linkname wasmimport_RequestOptionsResourceDrop github.com/wasmCloud/wadge/examples/go/http/bindings/wasi/http/types.wasmimport_RequestOptionsResourceDrop
func wasmimport_RequestOptionsResourceDrop(self0 uint32) {
	var __p runtime.Pinner
	defer __p.Unpin()
	if __err := wadge.WithCurrentInstance(func(__instance *wadge.Instance) error {
		return __instance.Call("wasi:http/types@0.2.0", "[resource-drop]request-options", func() unsafe.Pointer {
			ptr := unsafe.Pointer(&self0)
			__p.Pin(ptr)
			return ptr
		}())
	}); __err != nil {
		wadge.CurrentErrorHandler()(__err)
	}
	return
}

//go:linkname wasmimport_ResponseOutparamResourceDrop github.com/wasmCloud/wadge/examples/go/http/bindings/wasi/http/types.wasmimport_ResponseOutparamResourceDrop
func wasmimport_ResponseOutparamResourceDrop(self0 uint32) {
	var __p runtime.Pinner
	defer __p.Unpin()
	if __err := wadge.WithCurrentInstance(func(__instance *wadge.Instance) error {
		return __instance.Call("wasi:http/types@0.2.0", "[resource-drop]response-outparam", func() unsafe.Pointer {
			ptr := unsafe.Pointer(&self0)
			__p.Pin(ptr)
			return ptr
		}())
	}); __err != nil {
		wadge.CurrentErrorHandler()(__err)
	}
	return
}

//go:linkname wasmimport_FieldsFromList github.com/wasmCloud/wadge/examples/go/http/bindings/wasi/http/types.wasmimport_FieldsFromList
func wasmimport_FieldsFromList(entries0 *github_com__bytecodealliance__wasm___tools___go__cm.Tuple[github_com__wasmCloud__wadge__examples__go__http__bindings__wasi__http__types.FieldKey, github_com__wasmCloud__wadge__examples__go__http__bindings__wasi__http__types.FieldValue], entries1 uint32, result *github_com__bytecodealliance__wasm___tools___go__cm.Result[github_com__wasmCloud__wadge__examples__go__http__bindings__wasi__http__types.Fields, github_com__wasmCloud__wadge__examples__go__http__bindings__wasi__http__types.Fields, github_com__wasmCloud__wadge__examples__go__http__bindings__wasi__http__types.HeaderError]) {
	var __p runtime.Pinner
	defer __p.Unpin()
	if __err := wadge.WithCurrentInstance(func(__instance *wadge.Instance) error {
		return __instance.Call("wasi:http/types@0.2.0", "[static]fields.from-list", func() unsafe.Pointer {
			ptr := unsafe.Pointer(entries0)
			__p.Pin(ptr)
			return ptr
		}(), func() unsafe.Pointer {
			ptr := unsafe.Pointer(&entries1)
			__p.Pin(ptr)
			return ptr
		}(), func() unsafe.Pointer {
			ptr := unsafe.Pointer(result)
			__p.Pin(ptr)
			return ptr
		}())
	}); __err != nil {
		wadge.CurrentErrorHandler()(__err)
	}
	return
}

//go:linkname wasmimport_IncomingBodyFinish github.com/wasmCloud/wadge/examples/go/http/bindings/wasi/http/types.wasmimport_IncomingBodyFinish
func wasmimport_IncomingBodyFinish(this0 uint32) (result0 uint32) {
	var __p runtime.Pinner
	defer __p.Unpin()
	if __err := wadge.WithCurrentInstance(func(__instance *wadge.Instance) error {
		return __instance.Call("wasi:http/types@0.2.0", "[static]incoming-body.finish", func() unsafe.Pointer {
			ptr := unsafe.Pointer(&this0)
			__p.Pin(ptr)
			return ptr
		}(), func() unsafe.Pointer {
			ptr := unsafe.Pointer(&result0)
			__p.Pin(ptr)
			return ptr
		}())
	}); __err != nil {
		wadge.CurrentErrorHandler()(__err)
	}
	return
}

//go:linkname wasmimport_OutgoingBodyFinish github.com/wasmCloud/wadge/examples/go/http/bindings/wasi/http/types.wasmimport_OutgoingBodyFinish
func wasmimport_OutgoingBodyFinish(this0 uint32, trailers0 uint32, trailers1 uint32, result *github_com__bytecodealliance__wasm___tools___go__cm.Result[github_com__wasmCloud__wadge__examples__go__http__bindings__wasi__http__types.ErrorCode, struct{}, github_com__wasmCloud__wadge__examples__go__http__bindings__wasi__http__types.ErrorCode]) {
	var __p runtime.Pinner
	defer __p.Unpin()
	if __err := wadge.WithCurrentInstance(func(__instance *wadge.Instance) error {
		return __instance.Call("wasi:http/types@0.2.0", "[static]outgoing-body.finish", func() unsafe.Pointer {
			ptr := unsafe.Pointer(&this0)
			__p.Pin(ptr)
			return ptr
		}(), func() unsafe.Pointer {
			ptr := unsafe.Pointer(&trailers0)
			__p.Pin(ptr)
			return ptr
		}(), func() unsafe.Pointer {
			ptr := unsafe.Pointer(&trailers1)
			__p.Pin(ptr)
			return ptr
		}(), func() unsafe.Pointer {
			ptr := unsafe.Pointer(result)
			__p.Pin(ptr)
			return ptr
		}())
	}); __err != nil {
		wadge.CurrentErrorHandler()(__err)
	}
	return
}

//go:linkname wasmimport_ResponseOutparamSet github.com/wasmCloud/wadge/examples/go/http/bindings/wasi/http/types.wasmimport_ResponseOutparamSet
func wasmimport_ResponseOutparamSet(param0 uint32, response0 uint32, response1 uint32, response2 uint32, response3 uint64, response4 uint32, response5 uint32, response6 uint32, response7 uint32) {
	var __p runtime.Pinner
	defer __p.Unpin()
	if __err := wadge.WithCurrentInstance(func(__instance *wadge.Instance) error {
		return __instance.Call("wasi:http/types@0.2.0", "[static]response-outparam.set", func() unsafe.Pointer {
			ptr := unsafe.Pointer(&param0)
			__p.Pin(ptr)
			return ptr
		}(), func() unsafe.Pointer {
			ptr := unsafe.Pointer(&response0)
			__p.Pin(ptr)
			return ptr
		}(), func() unsafe.Pointer {
			ptr := unsafe.Pointer(&response1)
			__p.Pin(ptr)
			return ptr
		}(), func() unsafe.Pointer {
			ptr := unsafe.Pointer(&response2)
			__p.Pin(ptr)
			return ptr
		}(), func() unsafe.Pointer {
			ptr := unsafe.Pointer(&response3)
			__p.Pin(ptr)
			return ptr
		}(), func() unsafe.Pointer {
			ptr := unsafe.Pointer(&response4)
			__p.Pin(ptr)
			return ptr
		}(), func() unsafe.Pointer {
			ptr := unsafe.Pointer(&response5)
			__p.Pin(ptr)
			return ptr
		}(), func() unsafe.Pointer {
			ptr := unsafe.Pointer(&response6)
			__p.Pin(ptr)
			return ptr
		}(), func() unsafe.Pointer {
			ptr := unsafe.Pointer(&response7)
			__p.Pin(ptr)
			return ptr
		}())
	}); __err != nil {
		wadge.CurrentErrorHandler()(__err)
	}
	return
}

//go:linkname wasmimport_HTTPErrorCode github.com/wasmCloud/wadge/examples/go/http/bindings/wasi/http/types.wasmimport_HTTPErrorCode
func wasmimport_HTTPErrorCode(err0 uint32, result *github_com__bytecodealliance__wasm___tools___go__cm.Option[github_com__wasmCloud__wadge__examples__go__http__bindings__wasi__http__types.ErrorCode]) {
	var __p runtime.Pinner
	defer __p.Unpin()
	if __err := wadge.WithCurrentInstance(func(__instance *wadge.Instance) error {
		return __instance.Call("wasi:http/types@0.2.0", "http-error-code", func() unsafe.Pointer {
			ptr := unsafe.Pointer(&err0)
			__p.Pin(ptr)
			return ptr
		}(), func() unsafe.Pointer {
			ptr := unsafe.Pointer(result)
			__p.Pin(ptr)
			return ptr
		}())
	}); __err != nil {
		wadge.CurrentErrorHandler()(__err)
	}
	return
}

//go:linkname wasmimport_ErrorToDebugString github.com/wasmCloud/wadge/examples/go/http/bindings/wasi/io/error.wasmimport_ErrorToDebugString
func wasmimport_ErrorToDebugString(self0 uint32, result *string) {
	var __p runtime.Pinner
	defer __p.Unpin()
	if __err := wadge.WithCurrentInstance(func(__instance *wadge.Instance) error {
		return __instance.Call("wasi:io/error@0.2.0", "[method]error.to-debug-string", func() unsafe.Pointer {
			ptr := unsafe.Pointer(&self0)
			__p.Pin(ptr)
			return ptr
		}(), func() unsafe.Pointer {
			ptr := unsafe.Pointer(result)
			__p.Pin(ptr)
			return ptr
		}())
	}); __err != nil {
		wadge.CurrentErrorHandler()(__err)
	}
	return
}

//go:linkname wasmimport_ErrorResourceDrop github.com/wasmCloud/wadge/examples/go/http/bindings/wasi/io/error.wasmimport_ErrorResourceDrop
func wasmimport_ErrorResourceDrop(self0 uint32) {
	var __p runtime.Pinner
	defer __p.Unpin()
	if __err := wadge.WithCurrentInstance(func(__instance *wadge.Instance) error {
		return __instance.Call("wasi:io/error@0.2.0", "[resource-drop]error", func() unsafe.Pointer {
			ptr := unsafe.Pointer(&self0)
			__p.Pin(ptr)
			return ptr
		}())
	}); __err != nil {
		wadge.CurrentErrorHandler()(__err)
	}
	return
}

//go:linkname wasmimport_PollableBlock github.com/wasmCloud/wadge/examples/go/http/bindings/wasi/io/poll.wasmimport_PollableBlock
func wasmimport_PollableBlock(self0 uint32) {
	var __p runtime.Pinner
	defer __p.Unpin()
	if __err := wadge.WithCurrentInstance(func(__instance *wadge.Instance) error {
		return __instance.Call("wasi:io/poll@0.2.0", "[method]pollable.block", func() unsafe.Pointer {
			ptr := unsafe.Pointer(&self0)
			__p.Pin(ptr)
			return ptr
		}())
	}); __err != nil {
		wadge.CurrentErrorHandler()(__err)
	}
	return
}

//go:linkname wasmimport_PollableReady github.com/wasmCloud/wadge/examples/go/http/bindings/wasi/io/poll.wasmimport_PollableReady
func wasmimport_PollableReady(self0 uint32) (result0 uint32) {
	var __p runtime.Pinner
	defer __p.Unpin()
	if __err := wadge.WithCurrentInstance(func(__instance *wadge.Instance) error {
		return __instance.Call("wasi:io/poll@0.2.0", "[method]pollable.ready", func() unsafe.Pointer {
			ptr := unsafe.Pointer(&self0)
			__p.Pin(ptr)
			return ptr
		}(), func() unsafe.Pointer {
			ptr := unsafe.Pointer(&result0)
			__p.Pin(ptr)
			return ptr
		}())
	}); __err != nil {
		wadge.CurrentErrorHandler()(__err)
	}
	return
}

//go:linkname wasmimport_PollableResourceDrop github.com/wasmCloud/wadge/examples/go/http/bindings/wasi/io/poll.wasmimport_PollableResourceDrop
func wasmimport_PollableResourceDrop(self0 uint32) {
	var __p runtime.Pinner
	defer __p.Unpin()
	if __err := wadge.WithCurrentInstance(func(__instance *wadge.Instance) error {
		return __instance.Call("wasi:io/poll@0.2.0", "[resource-drop]pollable", func() unsafe.Pointer {
			ptr := unsafe.Pointer(&self0)
			__p.Pin(ptr)
			return ptr
		}())
	}); __err != nil {
		wadge.CurrentErrorHandler()(__err)
	}
	return
}

//go:linkname wasmimport_Poll github.com/wasmCloud/wadge/examples/go/http/bindings/wasi/io/poll.wasmimport_Poll
func wasmimport_Poll(in0 *github_com__wasmCloud__wadge__examples__go__http__bindings__wasi__io__poll.Pollable, in1 uint32, result *github_com__bytecodealliance__wasm___tools___go__cm.List[uint32]) {
	var __p runtime.Pinner
	defer __p.Unpin()
	if __err := wadge.WithCurrentInstance(func(__instance *wadge.Instance) error {
		return __instance.Call("wasi:io/poll@0.2.0", "poll", func() unsafe.Pointer {
			ptr := unsafe.Pointer(in0)
			__p.Pin(ptr)
			return ptr
		}(), func() unsafe.Pointer {
			ptr := unsafe.Pointer(&in1)
			__p.Pin(ptr)
			return ptr
		}(), func() unsafe.Pointer {
			ptr := unsafe.Pointer(result)
			__p.Pin(ptr)
			return ptr
		}())
	}); __err != nil {
		wadge.CurrentErrorHandler()(__err)
	}
	return
}

//go:linkname wasmimport_InputStreamBlockingRead github.com/wasmCloud/wadge/examples/go/http/bindings/wasi/io/streams.wasmimport_InputStreamBlockingRead
func wasmimport_InputStreamBlockingRead(self0 uint32, len0 uint64, result *github_com__bytecodealliance__wasm___tools___go__cm.Result[github_com__bytecodealliance__wasm___tools___go__cm.List[uint8], github_com__bytecodealliance__wasm___tools___go__cm.List[uint8], github_com__wasmCloud__wadge__examples__go__http__bindings__wasi__io__streams.StreamError]) {
	var __p runtime.Pinner
	defer __p.Unpin()
	if __err := wadge.WithCurrentInstance(func(__instance *wadge.Instance) error {
		return __instance.Call("wasi:io/streams@0.2.0", "[method]input-stream.blocking-read", func() unsafe.Pointer {
			ptr := unsafe.Pointer(&self0)
			__p.Pin(ptr)
			return ptr
		}(), func() unsafe.Pointer {
			ptr := unsafe.Pointer(&len0)
			__p.Pin(ptr)
			return ptr
		}(), func() unsafe.Pointer {
			ptr := unsafe.Pointer(result)
			__p.Pin(ptr)
			return ptr
		}())
	}); __err != nil {
		wadge.CurrentErrorHandler()(__err)
	}
	return
}

//go:linkname wasmimport_InputStreamBlockingSkip github.com/wasmCloud/wadge/examples/go/http/bindings/wasi/io/streams.wasmimport_InputStreamBlockingSkip
func wasmimport_InputStreamBlockingSkip(self0 uint32, len0 uint64, result *github_com__bytecodealliance__wasm___tools___go__cm.Result[uint64, uint64, github_com__wasmCloud__wadge__examples__go__http__bindings__wasi__io__streams.StreamError]) {
	var __p runtime.Pinner
	defer __p.Unpin()
	if __err := wadge.WithCurrentInstance(func(__instance *wadge.Instance) error {
		return __instance.Call("wasi:io/streams@0.2.0", "[method]input-stream.blocking-skip", func() unsafe.Pointer {
			ptr := unsafe.Pointer(&self0)
			__p.Pin(ptr)
			return ptr
		}(), func() unsafe.Pointer {
			ptr := unsafe.Pointer(&len0)
			__p.Pin(ptr)
			return ptr
		}(), func() unsafe.Pointer {
			ptr := unsafe.Pointer(result)
			__p.Pin(ptr)
			return ptr
		}())
	}); __err != nil {
		wadge.CurrentErrorHandler()(__err)
	}
	return
}

//go:linkname wasmimport_InputStreamRead github.com/wasmCloud/wadge/examples/go/http/bindings/wasi/io/streams.wasmimport_InputStreamRead
func wasmimport_InputStreamRead(self0 uint32, len0 uint64, result *github_com__bytecodealliance__wasm___tools___go__cm.Result[github_com__bytecodealliance__wasm___tools___go__cm.List[uint8], github_com__bytecodealliance__wasm___tools___go__cm.List[uint8], github_com__wasmCloud__wadge__examples__go__http__bindings__wasi__io__streams.StreamError]) {
	var __p runtime.Pinner
	defer __p.Unpin()
	if __err := wadge.WithCurrentInstance(func(__instance *wadge.Instance) error {
		return __instance.Call("wasi:io/streams@0.2.0", "[method]input-stream.read", func() unsafe.Pointer {
			ptr := unsafe.Pointer(&self0)
			__p.Pin(ptr)
			return ptr
		}(), func() unsafe.Pointer {
			ptr := unsafe.Pointer(&len0)
			__p.Pin(ptr)
			return ptr
		}(), func() unsafe.Pointer {
			ptr := unsafe.Pointer(result)
			__p.Pin(ptr)
			return ptr
		}())
	}); __err != nil {
		wadge.CurrentErrorHandler()(__err)
	}
	return
}

//go:linkname wasmimport_InputStreamSkip github.com/wasmCloud/wadge/examples/go/http/bindings/wasi/io/streams.wasmimport_InputStreamSkip
func wasmimport_InputStreamSkip(self0 uint32, len0 uint64, result *github_com__bytecodealliance__wasm___tools___go__cm.Result[uint64, uint64, github_com__wasmCloud__wadge__examples__go__http__bindings__wasi__io__streams.StreamError]) {
	var __p runtime.Pinner
	defer __p.Unpin()
	if __err := wadge.WithCurrentInstance(func(__instance *wadge.Instance) error {
		return __instance.Call("wasi:io/streams@0.2.0", "[method]input-stream.skip", func() unsafe.Pointer {
			ptr := unsafe.Pointer(&self0)
			__p.Pin(ptr)
			return ptr
		}(), func() unsafe.Pointer {
			ptr := unsafe.Pointer(&len0)
			__p.Pin(ptr)
			return ptr
		}(), func() unsafe.Pointer {
			ptr := unsafe.Pointer(result)
			__p.Pin(ptr)
			return ptr
		}())
	}); __err != nil {
		wadge.CurrentErrorHandler()(__err)
	}
	return
}

//go:linkname wasmimport_InputStreamSubscribe github.com/wasmCloud/wadge/examples/go/http/bindings/wasi/io/streams.wasmimport_InputStreamSubscribe
func wasmimport_InputStreamSubscribe(self0 uint32) (result0 uint32) {
	var __p runtime.Pinner
	defer __p.Unpin()
	if __err := wadge.WithCurrentInstance(func(__instance *wadge.Instance) error {
		return __instance.Call("wasi:io/streams@0.2.0", "[method]input-stream.subscribe", func() unsafe.Pointer {
			ptr := unsafe.Pointer(&self0)
			__p.Pin(ptr)
			return ptr
		}(), func() unsafe.Pointer {
			ptr := unsafe.Pointer(&result0)
			__p.Pin(ptr)
			return ptr
		}())
	}); __err != nil {
		wadge.CurrentErrorHandler()(__err)
	}
	return
}

//go:linkname wasmimport_OutputStreamBlockingFlush github.com/wasmCloud/wadge/examples/go/http/bindings/wasi/io/streams.wasmimport_OutputStreamBlockingFlush
func wasmimport_OutputStreamBlockingFlush(self0 uint32, result *github_com__bytecodealliance__wasm___tools___go__cm.Result[github_com__wasmCloud__wadge__examples__go__http__bindings__wasi__io__streams.StreamError, struct{}, github_com__wasmCloud__wadge__examples__go__http__bindings__wasi__io__streams.StreamError]) {
	var __p runtime.Pinner
	defer __p.Unpin()
	if __err := wadge.WithCurrentInstance(func(__instance *wadge.Instance) error {
		return __instance.Call("wasi:io/streams@0.2.0", "[method]output-stream.blocking-flush", func() unsafe.Pointer {
			ptr := unsafe.Pointer(&self0)
			__p.Pin(ptr)
			return ptr
		}(), func() unsafe.Pointer {
			ptr := unsafe.Pointer(result)
			__p.Pin(ptr)
			return ptr
		}())
	}); __err != nil {
		wadge.CurrentErrorHandler()(__err)
	}
	return
}

//go:linkname wasmimport_OutputStreamBlockingSplice github.com/wasmCloud/wadge/examples/go/http/bindings/wasi/io/streams.wasmimport_OutputStreamBlockingSplice
func wasmimport_OutputStreamBlockingSplice(self0 uint32, src0 uint32, len0 uint64, result *github_com__bytecodealliance__wasm___tools___go__cm.Result[uint64, uint64, github_com__wasmCloud__wadge__examples__go__http__bindings__wasi__io__streams.StreamError]) {
	var __p runtime.Pinner
	defer __p.Unpin()
	if __err := wadge.WithCurrentInstance(func(__instance *wadge.Instance) error {
		return __instance.Call("wasi:io/streams@0.2.0", "[method]output-stream.blocking-splice", func() unsafe.Pointer {
			ptr := unsafe.Pointer(&self0)
			__p.Pin(ptr)
			return ptr
		}(), func() unsafe.Pointer {
			ptr := unsafe.Pointer(&src0)
			__p.Pin(ptr)
			return ptr
		}(), func() unsafe.Pointer {
			ptr := unsafe.Pointer(&len0)
			__p.Pin(ptr)
			return ptr
		}(), func() unsafe.Pointer {
			ptr := unsafe.Pointer(result)
			__p.Pin(ptr)
			return ptr
		}())
	}); __err != nil {
		wadge.CurrentErrorHandler()(__err)
	}
	return
}

//go:linkname wasmimport_OutputStreamBlockingWriteAndFlush github.com/wasmCloud/wadge/examples/go/http/bindings/wasi/io/streams.wasmimport_OutputStreamBlockingWriteAndFlush
func wasmimport_OutputStreamBlockingWriteAndFlush(self0 uint32, contents0 *uint8, contents1 uint32, result *github_com__bytecodealliance__wasm___tools___go__cm.Result[github_com__wasmCloud__wadge__examples__go__http__bindings__wasi__io__streams.StreamError, struct{}, github_com__wasmCloud__wadge__examples__go__http__bindings__wasi__io__streams.StreamError]) {
	var __p runtime.Pinner
	defer __p.Unpin()
	if __err := wadge.WithCurrentInstance(func(__instance *wadge.Instance) error {
		return __instance.Call("wasi:io/streams@0.2.0", "[method]output-stream.blocking-write-and-flush", func() unsafe.Pointer {
			ptr := unsafe.Pointer(&self0)
			__p.Pin(ptr)
			return ptr
		}(), func() unsafe.Pointer {
			ptr := unsafe.Pointer(contents0)
			__p.Pin(ptr)
			return ptr
		}(), func() unsafe.Pointer {
			ptr := unsafe.Pointer(&contents1)
			__p.Pin(ptr)
			return ptr
		}(), func() unsafe.Pointer {
			ptr := unsafe.Pointer(result)
			__p.Pin(ptr)
			return ptr
		}())
	}); __err != nil {
		wadge.CurrentErrorHandler()(__err)
	}
	return
}

//go:linkname wasmimport_OutputStreamBlockingWriteZeroesAndFlush github.com/wasmCloud/wadge/examples/go/http/bindings/wasi/io/streams.wasmimport_OutputStreamBlockingWriteZeroesAndFlush
func wasmimport_OutputStreamBlockingWriteZeroesAndFlush(self0 uint32, len0 uint64, result *github_com__bytecodealliance__wasm___tools___go__cm.Result[github_com__wasmCloud__wadge__examples__go__http__bindings__wasi__io__streams.StreamError, struct{}, github_com__wasmCloud__wadge__examples__go__http__bindings__wasi__io__streams.StreamError]) {
	var __p runtime.Pinner
	defer __p.Unpin()
	if __err := wadge.WithCurrentInstance(func(__instance *wadge.Instance) error {
		return __instance.Call("wasi:io/streams@0.2.0", "[method]output-stream.blocking-write-zeroes-and-flush", func() unsafe.Pointer {
			ptr := unsafe.Pointer(&self0)
			__p.Pin(ptr)
			return ptr
		}(), func() unsafe.Pointer {
			ptr := unsafe.Pointer(&len0)
			__p.Pin(ptr)
			return ptr
		}(), func() unsafe.Pointer {
			ptr := unsafe.Pointer(result)
			__p.Pin(ptr)
			return ptr
		}())
	}); __err != nil {
		wadge.CurrentErrorHandler()(__err)
	}
	return
}

//go:linkname wasmimport_OutputStreamCheckWrite github.com/wasmCloud/wadge/examples/go/http/bindings/wasi/io/streams.wasmimport_OutputStreamCheckWrite
func wasmimport_OutputStreamCheckWrite(self0 uint32, result *github_com__bytecodealliance__wasm___tools___go__cm.Result[uint64, uint64, github_com__wasmCloud__wadge__examples__go__http__bindings__wasi__io__streams.StreamError]) {
	var __p runtime.Pinner
	defer __p.Unpin()
	if __err := wadge.WithCurrentInstance(func(__instance *wadge.Instance) error {
		return __instance.Call("wasi:io/streams@0.2.0", "[method]output-stream.check-write", func() unsafe.Pointer {
			ptr := unsafe.Pointer(&self0)
			__p.Pin(ptr)
			return ptr
		}(), func() unsafe.Pointer {
			ptr := unsafe.Pointer(result)
			__p.Pin(ptr)
			return ptr
		}())
	}); __err != nil {
		wadge.CurrentErrorHandler()(__err)
	}
	return
}

//go:linkname wasmimport_OutputStreamFlush github.com/wasmCloud/wadge/examples/go/http/bindings/wasi/io/streams.wasmimport_OutputStreamFlush
func wasmimport_OutputStreamFlush(self0 uint32, result *github_com__bytecodealliance__wasm___tools___go__cm.Result[github_com__wasmCloud__wadge__examples__go__http__bindings__wasi__io__streams.StreamError, struct{}, github_com__wasmCloud__wadge__examples__go__http__bindings__wasi__io__streams.StreamError]) {
	var __p runtime.Pinner
	defer __p.Unpin()
	if __err := wadge.WithCurrentInstance(func(__instance *wadge.Instance) error {
		return __instance.Call("wasi:io/streams@0.2.0", "[method]output-stream.flush", func() unsafe.Pointer {
			ptr := unsafe.Pointer(&self0)
			__p.Pin(ptr)
			return ptr
		}(), func() unsafe.Pointer {
			ptr := unsafe.Pointer(result)
			__p.Pin(ptr)
			return ptr
		}())
	}); __err != nil {
		wadge.CurrentErrorHandler()(__err)
	}
	return
}

//go:linkname wasmimport_OutputStreamSplice github.com/wasmCloud/wadge/examples/go/http/bindings/wasi/io/streams.wasmimport_OutputStreamSplice
func wasmimport_OutputStreamSplice(self0 uint32, src0 uint32, len0 uint64, result *github_com__bytecodealliance__wasm___tools___go__cm.Result[uint64, uint64, github_com__wasmCloud__wadge__examples__go__http__bindings__wasi__io__streams.StreamError]) {
	var __p runtime.Pinner
	defer __p.Unpin()
	if __err := wadge.WithCurrentInstance(func(__instance *wadge.Instance) error {
		return __instance.Call("wasi:io/streams@0.2.0", "[method]output-stream.splice", func() unsafe.Pointer {
			ptr := unsafe.Pointer(&self0)
			__p.Pin(ptr)
			return ptr
		}(), func() unsafe.Pointer {
			ptr := unsafe.Pointer(&src0)
			__p.Pin(ptr)
			return ptr
		}(), func() unsafe.Pointer {
			ptr := unsafe.Pointer(&len0)
			__p.Pin(ptr)
			return ptr
		}(), func() unsafe.Pointer {
			ptr := unsafe.Pointer(result)
			__p.Pin(ptr)
			return ptr
		}())
	}); __err != nil {
		wadge.CurrentErrorHandler()(__err)
	}
	return
}

//go:linkname wasmimport_OutputStreamSubscribe github.com/wasmCloud/wadge/examples/go/http/bindings/wasi/io/streams.wasmimport_OutputStreamSubscribe
func wasmimport_OutputStreamSubscribe(self0 uint32) (result0 uint32) {
	var __p runtime.Pinner
	defer __p.Unpin()
	if __err := wadge.WithCurrentInstance(func(__instance *wadge.Instance) error {
		return __instance.Call("wasi:io/streams@0.2.0", "[method]output-stream.subscribe", func() unsafe.Pointer {
			ptr := unsafe.Pointer(&self0)
			__p.Pin(ptr)
			return ptr
		}(), func() unsafe.Pointer {
			ptr := unsafe.Pointer(&result0)
			__p.Pin(ptr)
			return ptr
		}())
	}); __err != nil {
		wadge.CurrentErrorHandler()(__err)
	}
	return
}

//go:linkname wasmimport_OutputStreamWrite github.com/wasmCloud/wadge/examples/go/http/bindings/wasi/io/streams.wasmimport_OutputStreamWrite
func wasmimport_OutputStreamWrite(self0 uint32, contents0 *uint8, contents1 uint32, result *github_com__bytecodealliance__wasm___tools___go__cm.Result[github_com__wasmCloud__wadge__examples__go__http__bindings__wasi__io__streams.StreamError, struct{}, github_com__wasmCloud__wadge__examples__go__http__bindings__wasi__io__streams.StreamError]) {
	var __p runtime.Pinner
	defer __p.Unpin()
	if __err := wadge.WithCurrentInstance(func(__instance *wadge.Instance) error {
		return __instance.Call("wasi:io/streams@0.2.0", "[method]output-stream.write", func() unsafe.Pointer {
			ptr := unsafe.Pointer(&self0)
			__p.Pin(ptr)
			return ptr
		}(), func() unsafe.Pointer {
			ptr := unsafe.Pointer(contents0)
			__p.Pin(ptr)
			return ptr
		}(), func() unsafe.Pointer {
			ptr := unsafe.Pointer(&contents1)
			__p.Pin(ptr)
			return ptr
		}(), func() unsafe.Pointer {
			ptr := unsafe.Pointer(result)
			__p.Pin(ptr)
			return ptr
		}())
	}); __err != nil {
		wadge.CurrentErrorHandler()(__err)
	}
	return
}

//go:linkname wasmimport_OutputStreamWriteZeroes github.com/wasmCloud/wadge/examples/go/http/bindings/wasi/io/streams.wasmimport_OutputStreamWriteZeroes
func wasmimport_OutputStreamWriteZeroes(self0 uint32, len0 uint64, result *github_com__bytecodealliance__wasm___tools___go__cm.Result[github_com__wasmCloud__wadge__examples__go__http__bindings__wasi__io__streams.StreamError, struct{}, github_com__wasmCloud__wadge__examples__go__http__bindings__wasi__io__streams.StreamError]) {
	var __p runtime.Pinner
	defer __p.Unpin()
	if __err := wadge.WithCurrentInstance(func(__instance *wadge.Instance) error {
		return __instance.Call("wasi:io/streams@0.2.0", "[method]output-stream.write-zeroes", func() unsafe.Pointer {
			ptr := unsafe.Pointer(&self0)
			__p.Pin(ptr)
			return ptr
		}(), func() unsafe.Pointer {
			ptr := unsafe.Pointer(&len0)
			__p.Pin(ptr)
			return ptr
		}(), func() unsafe.Pointer {
			ptr := unsafe.Pointer(result)
			__p.Pin(ptr)
			return ptr
		}())
	}); __err != nil {
		wadge.CurrentErrorHandler()(__err)
	}
	return
}

//go:linkname wasmimport_InputStreamResourceDrop github.com/wasmCloud/wadge/examples/go/http/bindings/wasi/io/streams.wasmimport_InputStreamResourceDrop
func wasmimport_InputStreamResourceDrop(self0 uint32) {
	var __p runtime.Pinner
	defer __p.Unpin()
	if __err := wadge.WithCurrentInstance(func(__instance *wadge.Instance) error {
		return __instance.Call("wasi:io/streams@0.2.0", "[resource-drop]input-stream", func() unsafe.Pointer {
			ptr := unsafe.Pointer(&self0)
			__p.Pin(ptr)
			return ptr
		}())
	}); __err != nil {
		wadge.CurrentErrorHandler()(__err)
	}
	return
}

//go:linkname wasmimport_OutputStreamResourceDrop github.com/wasmCloud/wadge/examples/go/http/bindings/wasi/io/streams.wasmimport_OutputStreamResourceDrop
func wasmimport_OutputStreamResourceDrop(self0 uint32) {
	var __p runtime.Pinner
	defer __p.Unpin()
	if __err := wadge.WithCurrentInstance(func(__instance *wadge.Instance) error {
		return __instance.Call("wasi:io/streams@0.2.0", "[resource-drop]output-stream", func() unsafe.Pointer {
			ptr := unsafe.Pointer(&self0)
			__p.Pin(ptr)
			return ptr
		}())
	}); __err != nil {
		wadge.CurrentErrorHandler()(__err)
	}
	return
}
