// Code generated by wit-bindgen-go. DO NOT EDIT.

package sync

import (
	"go.bytecodealliance.org/cm"
)

// This file contains wasmimport and wasmexport declarations for "wadge-test:sync".

//go:wasmimport wadge-test:sync/sync [resource-drop]res
//go:noescape
func wasmimport_ResResourceDrop(self0 uint32)

//go:wasmimport wadge-test:sync/sync [constructor]res
//go:noescape
func wasmimport_NewRes() (result0 uint32)

//go:wasmimport wadge-test:sync/sync [static]res.make-list
//go:noescape
func wasmimport_ResMakeList(result *cm.List[Res])

//go:wasmimport wadge-test:sync/sync [method]res.foo
//go:noescape
func wasmimport_ResFoo(self0 uint32, result *string)

//go:wasmimport wadge-test:sync/sync identity-bool
//go:noescape
func wasmimport_IdentityBool(arg0 uint32) (result0 uint32)

//go:wasmimport wadge-test:sync/sync identity-s8
//go:noescape
func wasmimport_IdentityS8(arg0 uint32) (result0 uint32)

//go:wasmimport wadge-test:sync/sync identity-u8
//go:noescape
func wasmimport_IdentityU8(arg0 uint32) (result0 uint32)

//go:wasmimport wadge-test:sync/sync identity-s16
//go:noescape
func wasmimport_IdentityS16(arg0 uint32) (result0 uint32)

//go:wasmimport wadge-test:sync/sync identity-u16
//go:noescape
func wasmimport_IdentityU16(arg0 uint32) (result0 uint32)

//go:wasmimport wadge-test:sync/sync identity-s32
//go:noescape
func wasmimport_IdentityS32(arg0 uint32) (result0 uint32)

//go:wasmimport wadge-test:sync/sync identity-u32
//go:noescape
func wasmimport_IdentityU32(arg0 uint32) (result0 uint32)

//go:wasmimport wadge-test:sync/sync identity-s64
//go:noescape
func wasmimport_IdentityS64(arg0 uint64) (result0 uint64)

//go:wasmimport wadge-test:sync/sync identity-u64
//go:noescape
func wasmimport_IdentityU64(arg0 uint64) (result0 uint64)

//go:wasmimport wadge-test:sync/sync identity-f32
//go:noescape
func wasmimport_IdentityF32(arg0 float32) (result0 float32)

//go:wasmimport wadge-test:sync/sync identity-f64
//go:noescape
func wasmimport_IdentityF64(arg0 float64) (result0 float64)

//go:wasmimport wadge-test:sync/sync identity-char
//go:noescape
func wasmimport_IdentityChar(arg0 uint32) (result0 uint32)

//go:wasmimport wadge-test:sync/sync identity-string
//go:noescape
func wasmimport_IdentityString(arg0 *uint8, arg1 uint32, result *string)

//go:wasmimport wadge-test:sync/sync identity-flags
//go:noescape
func wasmimport_IdentityFlags(arg0 uint32) (result0 uint32)

//go:wasmimport wadge-test:sync/sync identity-enum
//go:noescape
func wasmimport_IdentityEnum(arg0 uint32) (result0 uint32)

//go:wasmimport wadge-test:sync/sync identity-variant
//go:noescape
func wasmimport_IdentityVariant(arg0 uint32, arg1 *uint8, arg2 uint32, result *Var)

//go:wasmimport wadge-test:sync/sync identity-option-string
//go:noescape
func wasmimport_IdentityOptionString(arg0 uint32, arg1 *uint8, arg2 uint32, result *cm.Option[string])

//go:wasmimport wadge-test:sync/sync identity-result-string
//go:noescape
func wasmimport_IdentityResultString(arg0 uint32, arg1 *uint8, arg2 uint32, result *cm.Result[string, string, struct{}])

//go:wasmimport wadge-test:sync/sync identity-record-primitives
//go:noescape
func wasmimport_IdentityRecordPrimitives(arg0 uint32, arg1 uint32, arg2 uint32, arg3 uint64, arg4 uint32, arg5 uint32, arg6 uint32, arg7 uint64, arg8 float32, arg9 float64, arg10 uint32, arg11 uint32, arg12 *uint8, arg13 uint32, result *Primitives)

//go:wasmimport wadge-test:sync/sync identity-record-rec
//go:noescape
func wasmimport_IdentityRecordRec(arg0 *uint8, arg1 uint32, result *Rec)

//go:wasmimport wadge-test:sync/sync identity-tuple
//go:noescape
func wasmimport_IdentityTuple(arg0 uint32, arg1 uint32, arg2 uint32, arg3 uint64, arg4 uint32, arg5 uint32, arg6 uint32, arg7 uint64, arg8 float32, arg9 float64, arg10 uint32, arg11 uint32, arg12 *uint8, arg13 uint32, result *cm.Tuple13[uint8, uint16, uint32, uint64, int8, int16, int32, int64, float32, float64, bool, rune, string])

//go:wasmimport wadge-test:sync/sync identity-list-bool
//go:noescape
func wasmimport_IdentityListBool(arg0 *bool, arg1 uint32, result *cm.List[bool])

//go:wasmimport wadge-test:sync/sync identity-list-u16
//go:noescape
func wasmimport_IdentityListU16(arg0 *uint16, arg1 uint32, result *cm.List[uint16])

//go:wasmimport wadge-test:sync/sync identity-list-string
//go:noescape
func wasmimport_IdentityListString(arg0 *string, arg1 uint32, result *cm.List[string])

//go:wasmimport wadge-test:sync/sync identity-list-enum
//go:noescape
func wasmimport_IdentityListEnum(arg0 *Foobar, arg1 uint32, result *cm.List[Foobar])

//go:wasmimport wadge-test:sync/sync identity-list-flags
//go:noescape
func wasmimport_IdentityListFlags(arg0 *Abc, arg1 uint32, result *cm.List[Abc])

//go:wasmimport wadge-test:sync/sync identity-list-record-primitives
//go:noescape
func wasmimport_IdentityListRecordPrimitives(arg0 *Primitives, arg1 uint32, result *cm.List[Primitives])

//go:wasmimport wadge-test:sync/sync identity-list-variant
//go:noescape
func wasmimport_IdentityListVariant(arg0 *Var, arg1 uint32, result *cm.List[Var])

//go:wasmimport wadge-test:sync/sync identity-list-option-string
//go:noescape
func wasmimport_IdentityListOptionString(arg0 *cm.Option[string], arg1 uint32, result *cm.List[cm.Option[string]])

//go:wasmimport wadge-test:sync/sync identity-list-result-string
//go:noescape
func wasmimport_IdentityListResultString(arg0 *cm.Result[string, string, struct{}], arg1 uint32, result *cm.List[cm.Result[string, string, struct{}]])

//go:wasmimport wadge-test:sync/sync identity-list-list-string
//go:noescape
func wasmimport_IdentityListListString(arg0 *cm.List[string], arg1 uint32, result *cm.List[cm.List[string]])

//go:wasmimport wadge-test:sync/sync identity-primitives
//go:noescape
func wasmimport_IdentityPrimitives(a0 uint32, b0 uint32, c0 uint32, d0 uint64, e0 uint32, f0 uint32, g0 uint32, h0 uint64, i0 float32, j0 float64, k0 uint32, l0 uint32, m0 *uint8, m1 uint32, result *cm.Tuple13[uint8, uint16, uint32, uint64, int8, int16, int32, int64, float32, float64, bool, rune, string])
