// Code generated by wit-bindgen-go. DO NOT EDIT.

package ext

import (
	"go.bytecodealliance.org/cm"
)

// This file contains wasmimport and wasmexport declarations for "wasiext:http@0.1.0".

//go:wasmimport wasiext:http/ext@0.1.0 new-response-outparam
//go:noescape
func wasmimport_NewResponseOutparam(result *cm.Tuple[ResponseOutparam, FutureIncomingResponse])

//go:wasmimport wasiext:http/ext@0.1.0 new-incoming-request
//go:noescape
func wasmimport_NewIncomingRequest(req0 uint32) (result0 uint32)
