// Code generated by wit-bindgen-go. DO NOT EDIT.

// Package fib represents the imported interface "wadge-test:fib/fib".
package fib

// Fib represents the imported function "fib".
//
//	fib: func(n: u32) -> u64
//
//go:nosplit
func Fib(n uint32) (result uint64) {
	n0 := (uint32)(n)
	result0 := wasmimport_Fib((uint32)(n0))
	result = (uint64)((uint64)(result0))
	return
}

//go:wasmimport wadge-test:fib/fib fib
//go:noescape
func wasmimport_Fib(n0 uint32) (result0 uint64)
