// Code generated by wit-bindgen-go. DO NOT EDIT.

package fib

// This file contains wasmimport and wasmexport declarations for "wadge-test:fib".

//go:wasmimport wadge-test:fib/fib fib
//go:noescape
func wasmimport_Fib(n0 uint32) (result0 uint64)
