// Code generated by wit-bindgen-go. DO NOT EDIT.

package network

// This file contains wasmimport and wasmexport declarations for "wasi:sockets@0.2.1".

//go:wasmimport wasi:sockets/network@0.2.1 [resource-drop]network
//go:noescape
func wasmimport_NetworkResourceDrop(self0 uint32)
