// Code generated by wit-bindgen-go. DO NOT EDIT.

package stdout

// This file contains wasmimport and wasmexport declarations for "wasi:cli@0.2.1".

//go:wasmimport wasi:cli/stdout@0.2.1 get-stdout
//go:noescape
func wasmimport_GetStdout() (result0 uint32)
