// Code generated by wit-bindgen-go. DO NOT EDIT.

package terminalinput

// This file contains wasmimport and wasmexport declarations for "wasi:cli@0.2.1".

//go:wasmimport wasi:cli/terminal-input@0.2.1 [resource-drop]terminal-input
//go:noescape
func wasmimport_TerminalInputResourceDrop(self0 uint32)
