// Code generated by wit-bindgen-go. DO NOT EDIT.

package poll

import (
	"github.com/bytecodealliance/wasm-tools-go/cm"
)

// This file contains wasmimport and wasmexport declarations for "wasi:io@0.2.1".

//go:wasmimport wasi:io/poll@0.2.1 [resource-drop]pollable
//go:noescape
func wasmimport_PollableResourceDrop(self0 uint32)

//go:wasmimport wasi:io/poll@0.2.1 [method]pollable.block
//go:noescape
func wasmimport_PollableBlock(self0 uint32)

//go:wasmimport wasi:io/poll@0.2.1 [method]pollable.ready
//go:noescape
func wasmimport_PollableReady(self0 uint32) (result0 uint32)

//go:wasmimport wasi:io/poll@0.2.1 poll
//go:noescape
func wasmimport_Poll(in0 *Pollable, in1 uint32, result *cm.List[uint32])
