package wadge-test:wasi;

world harness {
    include wadge-test:fib/host;
    include wadge-test:leftpad/host;

    export wasi:io/error@0.2.1;
    export wasi:io/poll@0.2.1;
    export wasi:io/streams@0.2.1;
}
