// Code generated by wit-bindgen-go. DO NOT EDIT.

// Package imports represents the world "wasi:http/imports@0.2.1".
//
// The `wasi:http/imports` world imports all the APIs for HTTP proxies.
// It is intended to be `include`d in other worlds.
package imports
