// Code generated by wit-bindgen-go. DO NOT EDIT.

package insecureseed

// This file contains wasmimport and wasmexport declarations for "wasi:random@0.2.1".

//go:wasmimport wasi:random/insecure-seed@0.2.1 insecure-seed
//go:noescape
func wasmimport_InsecureSeed(result *[2]uint64)
