// Code generated by wit-bindgen-go. DO NOT EDIT.

package leftpad

import (
	"github.com/wasmCloud/west/tests/go/wasi/bindings/wasi/io/streams"
	"unsafe"
)

// StreamErrorShape is used for storage in variant or result types.
type StreamErrorShape struct {
	shape [unsafe.Sizeof(streams.StreamError{})]byte
}
