// Code generated by wit-bindgen-go. DO NOT EDIT.

// Package leftpad represents the imported interface "west-test:leftpad/leftpad".
package leftpad

import (
	"github.com/bytecodealliance/wasm-tools-go/cm"
	"github.com/rvolosatovs/west/tests/go/wasi/bindings/wasi/io/streams"
)

// Leftpad represents the imported function "leftpad".
//
//	leftpad: func(in: input-stream, out: borrow<output-stream>, len: u64, c: char)
//	-> result<_, stream-error>
//
//go:nosplit
func Leftpad(in streams.InputStream, out streams.OutputStream, len_ uint64, c rune) (result cm.Result[streams.StreamError, struct{}, streams.StreamError]) {
	in0 := cm.Reinterpret[uint32](in)
	out0 := cm.Reinterpret[uint32](out)
	len0 := (uint64)(len_)
	c0 := (uint32)(c)
	wasmimport_Leftpad((uint32)(in0), (uint32)(out0), (uint64)(len0), (uint32)(c0), &result)
	return
}

//go:wasmimport west-test:leftpad/leftpad leftpad
//go:noescape
func wasmimport_Leftpad(in0 uint32, out0 uint32, len0 uint64, c0 uint32, result *cm.Result[streams.StreamError, struct{}, streams.StreamError])
