// Code generated by wit-bindgen-go. DO NOT EDIT.

package ipnamelookup

import (
	"github.com/rvolosatovs/west/tests/go/wasi/bindings/wasi/sockets/network"
	"github.com/ydnar/wasm-tools-go/cm"
	"unsafe"
)

// OptionIPAddressShape is used for storage in variant or result types.
type OptionIPAddressShape struct {
	shape [unsafe.Sizeof(cm.Option[network.IPAddress]{})]byte
}
